// GENERATED by gen_probe.py - compile-only probe of the vendored cIGZWin.h
#include "cIGZWin.h"

extern "C" void __cdecl probe_QueryInterface_1(cIGZWin* w) { w->QueryInterface((uint32_t)0, (void**)0); }
extern "C" void __cdecl probe_AddRef_1(cIGZWin* w) { w->AddRef(); }
extern "C" void __cdecl probe_Release_1(cIGZWin* w) { w->Release(); }
extern "C" void __cdecl probe_DoMessage_1(cIGZWin* w) { w->DoMessage(*(cGZMessage*)0); }
extern "C" void __cdecl probe_Init_1(cIGZWin* w) { w->Init(); }
extern "C" void __cdecl probe_Shutdown_1(cIGZWin* w) { w->Shutdown(); }
extern "C" void __cdecl probe_GetWindowManager_1(cIGZWin* w) { w->GetWindowManager(); }
extern "C" void __cdecl probe_SetWindowManager_1(cIGZWin* w) { w->SetWindowManager((cIGZWinMgr*)0); }
extern "C" void __cdecl probe_GetKeyboard_1(cIGZWin* w) { w->GetKeyboard(); }
extern "C" void __cdecl probe_SetKeyboard_1(cIGZWin* w) { w->SetKeyboard((cIGZKeyboard*)0); }
extern "C" void __cdecl probe_GetMainWindow_1(cIGZWin* w) { w->GetMainWindow(); }
extern "C" void __cdecl probe_GetParentWin_1(cIGZWin* w) { w->GetParentWin(); }
extern "C" void __cdecl probe_SetParentWin_1(cIGZWin* w) { w->SetParentWin((cIGZWin*)0); }
extern "C" void __cdecl probe_GetChildCount_1(cIGZWin* w) { w->GetChildCount(); }
extern "C" void __cdecl probe_ChildAdd_1(cIGZWin* w) { w->ChildAdd((cIGZWin*)0); }
extern "C" void __cdecl probe_ChildRemove_1(cIGZWin* w) { w->ChildRemove((cIGZWin*)0); }
extern "C" void __cdecl probe_ChildDelete_1(cIGZWin* w) { w->ChildDelete((cIGZWin*)0); }
extern "C" void __cdecl probe_ChildDeleteAbsolute_1(cIGZWin* w) { w->ChildDeleteAbsolute((cIGZWin*)0); }
extern "C" void __cdecl probe_ChildDeleteAll_1(cIGZWin* w) { w->ChildDeleteAll(); }
extern "C" void __cdecl probe_ChildExists_1(cIGZWin* w) { w->ChildExists((cIGZWin*)0); }
extern "C" void __cdecl probe_ChildExists_2(cIGZWin* w) { w->ChildExists((uint32_t)0); }
extern "C" void __cdecl probe_IsWinInParentChain_1(cIGZWin* w) { w->IsWinInParentChain((cIGZWin*)0); }
extern "C" void __cdecl probe_IsWinInChildChain_1(cIGZWin* w) { w->IsWinInChildChain((cIGZWin*)0); }
extern "C" void __cdecl probe_PullToFront_1(cIGZWin* w) { w->PullToFront(); }
extern "C" void __cdecl probe_SendToBack_1(cIGZWin* w) { w->SendToBack(); }
extern "C" void __cdecl probe_ChildToFront_1(cIGZWin* w) { w->ChildToFront((cIGZWin*)0); }
extern "C" void __cdecl probe_ChildToFront_2(cIGZWin* w) { w->ChildToFront((uint32_t)0); }
extern "C" void __cdecl probe_ChildToBack_1(cIGZWin* w) { w->ChildToBack((cIGZWin*)0); }
extern "C" void __cdecl probe_ChildStepFront_1(cIGZWin* w) { w->ChildStepFront((cIGZWin*)0); }
extern "C" void __cdecl probe_ChildStepBack_1(cIGZWin* w) { w->ChildStepBack((cIGZWin*)0); }
extern "C" void __cdecl probe_MoveRelativeTo_1(cIGZWin* w) { w->MoveRelativeTo((cIGZWin*)0, (bool)0); }
extern "C" void __cdecl probe_ChildMoveRelative_1(cIGZWin* w) { w->ChildMoveRelative((cIGZWin*)0, (cIGZWin*)0, (bool)0); }
extern "C" void __cdecl probe_EnumChildren_1(cIGZWin* w) { w->EnumChildren((uint32_t)0, (cIGZWin::EnumChildrenCallback)0, (void*)0); }
extern "C" void __cdecl probe_SortChildren_1(cIGZWin* w) { w->SortChildren((cIGZWin::SortChildrenCallback)0, (void*)0, (bool)0); }
extern "C" void __cdecl probe_GetChildWindowFromID_1(cIGZWin* w) { w->GetChildWindowFromID((uint32_t)0); }
extern "C" void __cdecl probe_GetChildWindowFromIDRecursive_1(cIGZWin* w) { w->GetChildWindowFromIDRecursive((uint32_t)0); }
extern "C" void __cdecl probe_GetChildAs_1(cIGZWin* w) { w->GetChildAs((uint32_t)0, (uint32_t)0, (void**)0); }
extern "C" void __cdecl probe_GetChildAsRecursive_1(cIGZWin* w) { w->GetChildAsRecursive((uint32_t)0, (uint32_t)0, (void**)0); }
extern "C" void __cdecl probe_GetWindowFromPoint_1(cIGZWin* w) { w->GetWindowFromPoint((int32_t)0, (int32_t)0); }
extern "C" void __cdecl probe_GetChildWindowFromPoint_1(cIGZWin* w) { w->GetChildWindowFromPoint((int32_t)0, (int32_t)0); }
extern "C" void __cdecl probe_GetChildWindowFromCursorPoint_1(cIGZWin* w) { w->GetChildWindowFromCursorPoint((int32_t)0, (int32_t)0); }
extern "C" void __cdecl probe_GetW_1(cIGZWin* w) { w->GetW(); }
extern "C" void __cdecl probe_GetH_1(cIGZWin* w) { w->GetH(); }
extern "C" void __cdecl probe_GetL_1(cIGZWin* w) { w->GetL(); }
extern "C" void __cdecl probe_GetT_1(cIGZWin* w) { w->GetT(); }
extern "C" void __cdecl probe_GetR_1(cIGZWin* w) { w->GetR(); }
extern "C" void __cdecl probe_GetB_1(cIGZWin* w) { w->GetB(); }
extern "C" void __cdecl probe_GetArea_1(cIGZWin* w) { w->GetArea(*(cRZRect*)0); }
extern "C" void __cdecl probe_GetArea_2(cIGZWin* w) { w->GetArea(); }
extern "C" void __cdecl probe_GetAreaAbsolute_1(cIGZWin* w) { w->GetAreaAbsolute(*(cRZRect*)0); }
extern "C" void __cdecl probe_GetAreaAbsolute_2(cIGZWin* w) { w->GetAreaAbsolute(); }
extern "C" void __cdecl probe_SetW_1(cIGZWin* w) { w->SetW((int32_t)0); }
extern "C" void __cdecl probe_SetH_1(cIGZWin* w) { w->SetH((int32_t)0); }
extern "C" void __cdecl probe_SetSize_1(cIGZWin* w) { w->SetSize((int32_t)0, (int32_t)0); }
extern "C" void __cdecl probe_SetArea_1(cIGZWin* w) { w->SetArea(*(cRZRect*)0); }
extern "C" void __cdecl probe_SetArea_2(cIGZWin* w) { w->SetArea((int32_t)0, (int32_t)0, (int32_t)0, (int32_t)0); }
extern "C" void __cdecl probe_GZWinMoveTo_1(cIGZWin* w) { w->GZWinMoveTo((int32_t)0, (int32_t)0); }
extern "C" void __cdecl probe_FitRectToWindow_1(cIGZWin* w) { w->FitRectToWindow(*(cRZRect*)0, (int32_t)0); }
extern "C" void __cdecl probe_ScreenToWindowCoordinates_1(cIGZWin* w) { w->ScreenToWindowCoordinates(*(int32_t*)0, *(int32_t*)0); }
extern "C" void __cdecl probe_WindowToScreenCoordinates_1(cIGZWin* w) { w->WindowToScreenCoordinates(*(int32_t*)0, *(int32_t*)0); }
extern "C" void __cdecl probe_WindowToWindowCoordinates_1(cIGZWin* w) { w->WindowToWindowCoordinates((cIGZWin*)0, *(int32_t*)0, *(int32_t*)0); }
extern "C" void __cdecl probe_IsPointInWindowScreenCoordinates_1(cIGZWin* w) { w->IsPointInWindowScreenCoordinates((int32_t)0, (int32_t)0); }
extern "C" void __cdecl probe_GetID_1(cIGZWin* w) { w->GetID(); }
extern "C" void __cdecl probe_SetID_1(cIGZWin* w) { w->SetID((uint32_t)0); }
extern "C" void __cdecl probe_GetInstanceID_1(cIGZWin* w) { w->GetInstanceID(); }
extern "C" void __cdecl probe_SetInstanceID_1(cIGZWin* w) { w->SetInstanceID((uint32_t)0); }
extern "C" void __cdecl probe_GetFlag_1(cIGZWin* w) { w->GetFlag((cIGZWin::tWinFlag)0); }
extern "C" void __cdecl probe_SetFlag_1(cIGZWin* w) { w->SetFlag((cIGZWin::tWinFlag)0, (bool)0); }
extern "C" void __cdecl probe_ShowWindow_1(cIGZWin* w) { w->ShowWindow(); }
extern "C" void __cdecl probe_HideWindow_1(cIGZWin* w) { w->HideWindow(); }
extern "C" void __cdecl probe_IsVisible_1(cIGZWin* w) { w->IsVisible(); }
extern "C" void __cdecl probe_IsEnabled_1(cIGZWin* w) { w->IsEnabled(); }
extern "C" void __cdecl probe_GetCaption_1(cIGZWin* w) { w->GetCaption(); }
extern "C" void __cdecl probe_SetCaption_1(cIGZWin* w) { w->SetCaption(*(cIGZString*)0); }
extern "C" void __cdecl probe_GetKeyboardAccelerator_1(cIGZWin* w) { w->GetKeyboardAccelerator(); }
extern "C" void __cdecl probe_SetKeyboardAccelerator_1(cIGZWin* w) { w->SetKeyboardAccelerator((cIGZWinKeyAccelerator*)0); }
extern "C" void __cdecl probe_AccelerateKeyboardMsg_1(cIGZWin* w) { w->AccelerateKeyboardMsg(); }
extern "C" void __cdecl probe_GetKeyEquivalent_1(cIGZWin* w) { w->GetKeyEquivalent(); }
extern "C" void __cdecl probe_SetKeyEquivalent_1(cIGZWin* w) { w->SetKeyEquivalent((uint32_t)0); }
extern "C" void __cdecl probe_CheckKeyEquivalent_1(cIGZWin* w) { w->CheckKeyEquivalent((uint32_t)0); }
extern "C" void __cdecl probe_MakeKeyEquivalent_1(cIGZWin* w) { w->MakeKeyEquivalent((uint32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_IsChildKeyEquivalent_1(cIGZWin* w) { w->IsChildKeyEquivalent((uint32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_ProcessCursorMessage_1(cIGZWin* w) { w->ProcessCursorMessage(*(cGZMessage*)0); }
extern "C" void __cdecl probe_UpdateCursor_1(cIGZWin* w) { w->UpdateCursor(); }
extern "C" void __cdecl probe_SetCursor_1(cIGZWin* w) { w->SetCursor((cIGZCursor*)0, (bool)0); }
extern "C" void __cdecl probe_SetNotificationTarget_1(cIGZWin* w) { w->SetNotificationTarget((cIGZWin*)0); }
extern "C" void __cdecl probe_GetNotificationTarget_1(cIGZWin* w) { w->GetNotificationTarget(); }
extern "C" void __cdecl probe_GZPaint_1(cIGZWin* w) { w->GZPaint(); }
extern "C" void __cdecl probe_Plot_1(cIGZWin* w) { w->Plot(); }
extern "C" void __cdecl probe_CalcAbsoluteArea_1(cIGZWin* w) { w->CalcAbsoluteArea(); }
extern "C" void __cdecl probe_InvalidateSelf_1(cIGZWin* w) { w->InvalidateSelf(); }
extern "C" void __cdecl probe_InvalidateSelfAndParents_1(cIGZWin* w) { w->InvalidateSelfAndParents(); }
extern "C" void __cdecl probe_GetDrawContext_1(cIGZWin* w) { w->GetDrawContext(); }
extern "C" void __cdecl probe_GetBufferToDrawTo_1(cIGZWin* w) { w->GetBufferToDrawTo(); }
extern "C" void __cdecl probe_SetBufferToDrawTo_1(cIGZWin* w) { w->SetBufferToDrawTo(); }
extern "C" void __cdecl probe_SetBufferToDrawToRecursive_1(cIGZWin* w) { w->SetBufferToDrawToRecursive(); }
extern "C" void __cdecl probe_SetAreaToDrawTo_1(cIGZWin* w) { w->SetAreaToDrawTo(); }
extern "C" void __cdecl probe_SetAreaToDrawToRecursive_1(cIGZWin* w) { w->SetAreaToDrawToRecursive(); }
extern "C" void __cdecl probe_GetAreaToDrawTo_1(cIGZWin* w) { w->GetAreaToDrawTo(); }
extern "C" void __cdecl probe_PrivateBuffer_1(cIGZWin* w) { w->PrivateBuffer((bool)0); }
extern "C" void __cdecl probe_GetPrivateBuffer_1(cIGZWin* w) { w->GetPrivateBuffer(); }
extern "C" void __cdecl probe_GetFillColor_1(cIGZWin* w) { w->GetFillColor(*(cRZColor*)0); }
extern "C" void __cdecl probe_GetFillColor_2(cIGZWin* w) { w->GetFillColor(); }
extern "C" void __cdecl probe_GetFillColor_3(cIGZWin* w) { w->GetFillColor(*(uint8_t*)0, *(uint8_t*)0, *(uint8_t*)0); }
extern "C" void __cdecl probe_SetFillColor_1(cIGZWin* w) { w->SetFillColor(*(cRZColor*)0); }
extern "C" void __cdecl probe_SetFillColor_2(cIGZWin* w) { w->SetFillColor((uint32_t)0); }
extern "C" void __cdecl probe_SetFillColor_3(cIGZWin* w) { w->SetFillColor((uint8_t)0, (uint8_t)0, (uint8_t)0); }
extern "C" void __cdecl probe_MakeFillColor_1(cIGZWin* w) { w->MakeFillColor((uint8_t)0, (uint8_t)0, (uint8_t)0); }
extern "C" void __cdecl probe_SetFadeEffectPeriod_1(cIGZWin* w) { w->SetFadeEffectPeriod((int32_t)0, (int32_t)0); }
extern "C" void __cdecl probe_GetFadeEffectPeriod_1(cIGZWin* w) { w->GetFadeEffectPeriod(*(int32_t*)0, *(int32_t*)0); }
extern "C" void __cdecl probe_SetShadeColor_1(cIGZWin* w) { w->SetShadeColor(*(cRZColor*)0); }
extern "C" void __cdecl probe_GetShadeColor_1(cIGZWin* w) { w->GetShadeColor(*(cRZColor*)0); }
extern "C" void __cdecl probe_GetParam_1(cIGZWin* w) { w->GetParam((uint32_t)0, (cIGZVariant**)0); }
extern "C" void __cdecl probe_SetParam_1(cIGZWin* w) { w->SetParam((uint32_t)0, (cIGZVariant*)0); }
extern "C" void __cdecl probe_EnumParams_1(cIGZWin* w) { w->EnumParams((cIGZWin::EnumParamsCallback)0, (void*)0); }
extern "C" void __cdecl probe_AddMessageFilter_1(cIGZWin* w) { w->AddMessageFilter((cIGZWinMessageFilter*)0); }
extern "C" void __cdecl probe_RemoveMessageFilter_1(cIGZWin* w) { w->RemoveMessageFilter((cIGZWinMessageFilter*)0); }
extern "C" void __cdecl probe_SetSize_2(cIGZWin* w) { w->SetSize(*(cRZPoint*)0); }
extern "C" void __cdecl probe_CenterWindowInRect_1(cIGZWin* w) { w->CenterWindowInRect(*(cRZRect*)0); }
extern "C" void __cdecl probe_CenterWindowInRect_2(cIGZWin* w) { w->CenterWindowInRect((cRZRect*)0); }
extern "C" void __cdecl probe_IsPointInWindowWindowCoordinates_1(cIGZWin* w) { w->IsPointInWindowWindowCoordinates((int32_t)0, (int32_t)0); }
extern "C" void __cdecl probe_IsPointInWindowParentCoordinates_1(cIGZWin* w) { w->IsPointInWindowParentCoordinates((int32_t)0, (int32_t)0); }
extern "C" void __cdecl probe_PlotComposite_1(cIGZWin* w) { w->PlotComposite(); }
extern "C" void __cdecl probe_PlotPresent_1(cIGZWin* w) { w->PlotPresent(); }
extern "C" void __cdecl probe_SetFillColorRGB_1(cIGZWin* w) { w->SetFillColorRGB((uint32_t)0); }
extern "C" void __cdecl probe_GetFillColorRGB_1(cIGZWin* w) { w->GetFillColorRGB(); }
extern "C" void __cdecl probe_ConvertPackedRGBToNative_1(cIGZWin* w) { w->ConvertPackedRGBToNative((uint32_t)0); }
extern "C" void __cdecl probe_ConvertNativeToPackedRGB_1(cIGZWin* w) { w->ConvertNativeToPackedRGB((uint32_t)0); }
extern "C" void __cdecl probe_GZOnCharacter_1(cIGZWin* w) { w->GZOnCharacter((int8_t)0); }
extern "C" void __cdecl probe_GZOnKeyDown_1(cIGZWin* w) { w->GZOnKeyDown((uint32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnKeyUp_1(cIGZWin* w) { w->GZOnKeyUp((uint32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnSetFocus_1(cIGZWin* w) { w->GZOnSetFocus((uint32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnKillFocus_1(cIGZWin* w) { w->GZOnKillFocus((cIGZWin*)0); }
extern "C" void __cdecl probe_GZOnMouseDownL_1(cIGZWin* w) { w->GZOnMouseDownL((int32_t)0, (int32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnMouseDownR_1(cIGZWin* w) { w->GZOnMouseDownR((int32_t)0, (int32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnMouseUpL_1(cIGZWin* w) { w->GZOnMouseUpL((int32_t)0, (int32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnMouseUpR_1(cIGZWin* w) { w->GZOnMouseUpR((int32_t)0, (int32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnMouseMove_1(cIGZWin* w) { w->GZOnMouseMove((int32_t)0, (int32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnMouseWheel_1(cIGZWin* w) { w->GZOnMouseWheel((int32_t)0, (int32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnCaptureChanged_1(cIGZWin* w) { w->GZOnCaptureChanged((cIGZWin*)0, (uint32_t)0, (uint32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnMouseEnter_1(cIGZWin* w) { w->GZOnMouseEnter((uint32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_GZOnMouseExit_1(cIGZWin* w) { w->GZOnMouseExit((uint32_t)0); }
extern "C" void __cdecl probe_GZOnCommand_1(cIGZWin* w) { w->GZOnCommand((uint32_t)0); }
extern "C" void __cdecl probe_SendMsg_1(cIGZWin* w) { w->SendMsg((cIGZWin*)0, *(cGZMessage*)0); }
extern "C" void __cdecl probe_SendMsg_2(cIGZWin* w) { w->SendMsg((cIGZWin*)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0); }
extern "C" void __cdecl probe_PostMsg_1(cIGZWin* w) { w->PostMsg((cIGZWin*)0, *(cGZMessage*)0); }
extern "C" void __cdecl probe_PostMsg_2(cIGZWin* w) { w->PostMsg((cIGZWin*)0, (uint32_t)0, (uint32_t)0, (uint32_t)0, (uint32_t)0); }

typedef bool (cIGZWin::*PM_QueryInterface_1)(uint32_t, void**);
extern "C" PM_QueryInterface_1 volatile pm_QueryInterface_1 = static_cast<PM_QueryInterface_1>(&cIGZWin::QueryInterface);
typedef uint32_t (cIGZWin::*PM_AddRef_1)();
extern "C" PM_AddRef_1 volatile pm_AddRef_1 = static_cast<PM_AddRef_1>(&cIGZWin::AddRef);
typedef uint32_t (cIGZWin::*PM_Release_1)();
extern "C" PM_Release_1 volatile pm_Release_1 = static_cast<PM_Release_1>(&cIGZWin::Release);
typedef bool (cIGZWin::*PM_DoMessage_1)(cGZMessage&);
extern "C" PM_DoMessage_1 volatile pm_DoMessage_1 = static_cast<PM_DoMessage_1>(&cIGZWin::DoMessage);
typedef bool (cIGZWin::*PM_Init_1)();
extern "C" PM_Init_1 volatile pm_Init_1 = static_cast<PM_Init_1>(&cIGZWin::Init);
typedef bool (cIGZWin::*PM_Shutdown_1)();
extern "C" PM_Shutdown_1 volatile pm_Shutdown_1 = static_cast<PM_Shutdown_1>(&cIGZWin::Shutdown);
typedef cIGZWinMgr* (cIGZWin::*PM_GetWindowManager_1)();
extern "C" PM_GetWindowManager_1 volatile pm_GetWindowManager_1 = static_cast<PM_GetWindowManager_1>(&cIGZWin::GetWindowManager);
typedef bool (cIGZWin::*PM_SetWindowManager_1)(cIGZWinMgr*);
extern "C" PM_SetWindowManager_1 volatile pm_SetWindowManager_1 = static_cast<PM_SetWindowManager_1>(&cIGZWin::SetWindowManager);
typedef cIGZKeyboard* (cIGZWin::*PM_GetKeyboard_1)();
extern "C" PM_GetKeyboard_1 volatile pm_GetKeyboard_1 = static_cast<PM_GetKeyboard_1>(&cIGZWin::GetKeyboard);
typedef bool (cIGZWin::*PM_SetKeyboard_1)(cIGZKeyboard*);
extern "C" PM_SetKeyboard_1 volatile pm_SetKeyboard_1 = static_cast<PM_SetKeyboard_1>(&cIGZWin::SetKeyboard);
typedef cIGZWin* (cIGZWin::*PM_GetMainWindow_1)();
extern "C" PM_GetMainWindow_1 volatile pm_GetMainWindow_1 = static_cast<PM_GetMainWindow_1>(&cIGZWin::GetMainWindow);
typedef cIGZWin* (cIGZWin::*PM_GetParentWin_1)();
extern "C" PM_GetParentWin_1 volatile pm_GetParentWin_1 = static_cast<PM_GetParentWin_1>(&cIGZWin::GetParentWin);
typedef bool (cIGZWin::*PM_SetParentWin_1)(cIGZWin*);
extern "C" PM_SetParentWin_1 volatile pm_SetParentWin_1 = static_cast<PM_SetParentWin_1>(&cIGZWin::SetParentWin);
typedef int32_t (cIGZWin::*PM_GetChildCount_1)();
extern "C" PM_GetChildCount_1 volatile pm_GetChildCount_1 = static_cast<PM_GetChildCount_1>(&cIGZWin::GetChildCount);
typedef bool (cIGZWin::*PM_ChildAdd_1)(cIGZWin*);
extern "C" PM_ChildAdd_1 volatile pm_ChildAdd_1 = static_cast<PM_ChildAdd_1>(&cIGZWin::ChildAdd);
typedef bool (cIGZWin::*PM_ChildRemove_1)(cIGZWin*);
extern "C" PM_ChildRemove_1 volatile pm_ChildRemove_1 = static_cast<PM_ChildRemove_1>(&cIGZWin::ChildRemove);
typedef bool (cIGZWin::*PM_ChildDelete_1)(cIGZWin*);
extern "C" PM_ChildDelete_1 volatile pm_ChildDelete_1 = static_cast<PM_ChildDelete_1>(&cIGZWin::ChildDelete);
typedef bool (cIGZWin::*PM_ChildDeleteAbsolute_1)(cIGZWin*);
extern "C" PM_ChildDeleteAbsolute_1 volatile pm_ChildDeleteAbsolute_1 = static_cast<PM_ChildDeleteAbsolute_1>(&cIGZWin::ChildDeleteAbsolute);
typedef bool (cIGZWin::*PM_ChildDeleteAll_1)();
extern "C" PM_ChildDeleteAll_1 volatile pm_ChildDeleteAll_1 = static_cast<PM_ChildDeleteAll_1>(&cIGZWin::ChildDeleteAll);
typedef bool (cIGZWin::*PM_ChildExists_1)(cIGZWin*);
extern "C" PM_ChildExists_1 volatile pm_ChildExists_1 = static_cast<PM_ChildExists_1>(&cIGZWin::ChildExists);
typedef bool (cIGZWin::*PM_ChildExists_2)(uint32_t);
extern "C" PM_ChildExists_2 volatile pm_ChildExists_2 = static_cast<PM_ChildExists_2>(&cIGZWin::ChildExists);
typedef bool (cIGZWin::*PM_IsWinInParentChain_1)(cIGZWin*);
extern "C" PM_IsWinInParentChain_1 volatile pm_IsWinInParentChain_1 = static_cast<PM_IsWinInParentChain_1>(&cIGZWin::IsWinInParentChain);
typedef bool (cIGZWin::*PM_IsWinInChildChain_1)(cIGZWin*);
extern "C" PM_IsWinInChildChain_1 volatile pm_IsWinInChildChain_1 = static_cast<PM_IsWinInChildChain_1>(&cIGZWin::IsWinInChildChain);
typedef bool (cIGZWin::*PM_PullToFront_1)();
extern "C" PM_PullToFront_1 volatile pm_PullToFront_1 = static_cast<PM_PullToFront_1>(&cIGZWin::PullToFront);
typedef bool (cIGZWin::*PM_SendToBack_1)();
extern "C" PM_SendToBack_1 volatile pm_SendToBack_1 = static_cast<PM_SendToBack_1>(&cIGZWin::SendToBack);
typedef bool (cIGZWin::*PM_ChildToFront_1)(cIGZWin*);
extern "C" PM_ChildToFront_1 volatile pm_ChildToFront_1 = static_cast<PM_ChildToFront_1>(&cIGZWin::ChildToFront);
typedef bool (cIGZWin::*PM_ChildToFront_2)(uint32_t);
extern "C" PM_ChildToFront_2 volatile pm_ChildToFront_2 = static_cast<PM_ChildToFront_2>(&cIGZWin::ChildToFront);
typedef bool (cIGZWin::*PM_ChildToBack_1)(cIGZWin*);
extern "C" PM_ChildToBack_1 volatile pm_ChildToBack_1 = static_cast<PM_ChildToBack_1>(&cIGZWin::ChildToBack);
typedef bool (cIGZWin::*PM_ChildStepFront_1)(cIGZWin*);
extern "C" PM_ChildStepFront_1 volatile pm_ChildStepFront_1 = static_cast<PM_ChildStepFront_1>(&cIGZWin::ChildStepFront);
typedef bool (cIGZWin::*PM_ChildStepBack_1)(cIGZWin*);
extern "C" PM_ChildStepBack_1 volatile pm_ChildStepBack_1 = static_cast<PM_ChildStepBack_1>(&cIGZWin::ChildStepBack);
typedef bool (cIGZWin::*PM_MoveRelativeTo_1)(cIGZWin*, bool);
extern "C" PM_MoveRelativeTo_1 volatile pm_MoveRelativeTo_1 = static_cast<PM_MoveRelativeTo_1>(&cIGZWin::MoveRelativeTo);
typedef bool (cIGZWin::*PM_ChildMoveRelative_1)(cIGZWin*, cIGZWin*, bool);
extern "C" PM_ChildMoveRelative_1 volatile pm_ChildMoveRelative_1 = static_cast<PM_ChildMoveRelative_1>(&cIGZWin::ChildMoveRelative);
typedef bool (cIGZWin::*PM_EnumChildren_1)(uint32_t, cIGZWin::EnumChildrenCallback, void*);
extern "C" PM_EnumChildren_1 volatile pm_EnumChildren_1 = static_cast<PM_EnumChildren_1>(&cIGZWin::EnumChildren);
typedef bool (cIGZWin::*PM_SortChildren_1)(cIGZWin::SortChildrenCallback, void*, bool);
extern "C" PM_SortChildren_1 volatile pm_SortChildren_1 = static_cast<PM_SortChildren_1>(&cIGZWin::SortChildren);
typedef cIGZWin* (cIGZWin::*PM_GetChildWindowFromID_1)(uint32_t);
extern "C" PM_GetChildWindowFromID_1 volatile pm_GetChildWindowFromID_1 = static_cast<PM_GetChildWindowFromID_1>(&cIGZWin::GetChildWindowFromID);
typedef cIGZWin* (cIGZWin::*PM_GetChildWindowFromIDRecursive_1)(uint32_t);
extern "C" PM_GetChildWindowFromIDRecursive_1 volatile pm_GetChildWindowFromIDRecursive_1 = static_cast<PM_GetChildWindowFromIDRecursive_1>(&cIGZWin::GetChildWindowFromIDRecursive);
typedef bool (cIGZWin::*PM_GetChildAs_1)(uint32_t, uint32_t, void**);
extern "C" PM_GetChildAs_1 volatile pm_GetChildAs_1 = static_cast<PM_GetChildAs_1>(&cIGZWin::GetChildAs);
typedef bool (cIGZWin::*PM_GetChildAsRecursive_1)(uint32_t, uint32_t, void**);
extern "C" PM_GetChildAsRecursive_1 volatile pm_GetChildAsRecursive_1 = static_cast<PM_GetChildAsRecursive_1>(&cIGZWin::GetChildAsRecursive);
typedef cIGZWin* (cIGZWin::*PM_GetWindowFromPoint_1)(int32_t, int32_t);
extern "C" PM_GetWindowFromPoint_1 volatile pm_GetWindowFromPoint_1 = static_cast<PM_GetWindowFromPoint_1>(&cIGZWin::GetWindowFromPoint);
typedef cIGZWin* (cIGZWin::*PM_GetChildWindowFromPoint_1)(int32_t, int32_t);
extern "C" PM_GetChildWindowFromPoint_1 volatile pm_GetChildWindowFromPoint_1 = static_cast<PM_GetChildWindowFromPoint_1>(&cIGZWin::GetChildWindowFromPoint);
typedef cIGZWin* (cIGZWin::*PM_GetChildWindowFromCursorPoint_1)(int32_t, int32_t);
extern "C" PM_GetChildWindowFromCursorPoint_1 volatile pm_GetChildWindowFromCursorPoint_1 = static_cast<PM_GetChildWindowFromCursorPoint_1>(&cIGZWin::GetChildWindowFromCursorPoint);
typedef int32_t (cIGZWin::*PM_GetW_1)() const;
extern "C" PM_GetW_1 volatile pm_GetW_1 = static_cast<PM_GetW_1>(&cIGZWin::GetW);
typedef int32_t (cIGZWin::*PM_GetH_1)() const;
extern "C" PM_GetH_1 volatile pm_GetH_1 = static_cast<PM_GetH_1>(&cIGZWin::GetH);
typedef int32_t (cIGZWin::*PM_GetL_1)() const;
extern "C" PM_GetL_1 volatile pm_GetL_1 = static_cast<PM_GetL_1>(&cIGZWin::GetL);
typedef int32_t (cIGZWin::*PM_GetT_1)() const;
extern "C" PM_GetT_1 volatile pm_GetT_1 = static_cast<PM_GetT_1>(&cIGZWin::GetT);
typedef int32_t (cIGZWin::*PM_GetR_1)() const;
extern "C" PM_GetR_1 volatile pm_GetR_1 = static_cast<PM_GetR_1>(&cIGZWin::GetR);
typedef int32_t (cIGZWin::*PM_GetB_1)() const;
extern "C" PM_GetB_1 volatile pm_GetB_1 = static_cast<PM_GetB_1>(&cIGZWin::GetB);
typedef bool (cIGZWin::*PM_GetArea_1)(cRZRect&) const;
extern "C" PM_GetArea_1 volatile pm_GetArea_1 = static_cast<PM_GetArea_1>(&cIGZWin::GetArea);
typedef int32_t* (cIGZWin::*PM_GetArea_2)() const;
extern "C" PM_GetArea_2 volatile pm_GetArea_2 = static_cast<PM_GetArea_2>(&cIGZWin::GetArea);
typedef bool (cIGZWin::*PM_GetAreaAbsolute_1)(cRZRect&) const;
extern "C" PM_GetAreaAbsolute_1 volatile pm_GetAreaAbsolute_1 = static_cast<PM_GetAreaAbsolute_1>(&cIGZWin::GetAreaAbsolute);
typedef int32_t* (cIGZWin::*PM_GetAreaAbsolute_2)() const;
extern "C" PM_GetAreaAbsolute_2 volatile pm_GetAreaAbsolute_2 = static_cast<PM_GetAreaAbsolute_2>(&cIGZWin::GetAreaAbsolute);
typedef bool (cIGZWin::*PM_SetW_1)(int32_t);
extern "C" PM_SetW_1 volatile pm_SetW_1 = static_cast<PM_SetW_1>(&cIGZWin::SetW);
typedef bool (cIGZWin::*PM_SetH_1)(int32_t);
extern "C" PM_SetH_1 volatile pm_SetH_1 = static_cast<PM_SetH_1>(&cIGZWin::SetH);
typedef bool (cIGZWin::*PM_SetSize_1)(int32_t, int32_t);
extern "C" PM_SetSize_1 volatile pm_SetSize_1 = static_cast<PM_SetSize_1>(&cIGZWin::SetSize);
typedef bool (cIGZWin::*PM_SetArea_1)(const cRZRect&);
extern "C" PM_SetArea_1 volatile pm_SetArea_1 = static_cast<PM_SetArea_1>(&cIGZWin::SetArea);
typedef bool (cIGZWin::*PM_SetArea_2)(int32_t, int32_t, int32_t, int32_t);
extern "C" PM_SetArea_2 volatile pm_SetArea_2 = static_cast<PM_SetArea_2>(&cIGZWin::SetArea);
typedef bool (cIGZWin::*PM_GZWinMoveTo_1)(int32_t, int32_t);
extern "C" PM_GZWinMoveTo_1 volatile pm_GZWinMoveTo_1 = static_cast<PM_GZWinMoveTo_1>(&cIGZWin::GZWinMoveTo);
typedef bool (cIGZWin::*PM_FitRectToWindow_1)(cRZRect&, int32_t);
extern "C" PM_FitRectToWindow_1 volatile pm_FitRectToWindow_1 = static_cast<PM_FitRectToWindow_1>(&cIGZWin::FitRectToWindow);
typedef bool (cIGZWin::*PM_ScreenToWindowCoordinates_1)(int32_t&, int32_t&) const;
extern "C" PM_ScreenToWindowCoordinates_1 volatile pm_ScreenToWindowCoordinates_1 = static_cast<PM_ScreenToWindowCoordinates_1>(&cIGZWin::ScreenToWindowCoordinates);
typedef bool (cIGZWin::*PM_WindowToScreenCoordinates_1)(int32_t&, int32_t&) const;
extern "C" PM_WindowToScreenCoordinates_1 volatile pm_WindowToScreenCoordinates_1 = static_cast<PM_WindowToScreenCoordinates_1>(&cIGZWin::WindowToScreenCoordinates);
typedef bool (cIGZWin::*PM_WindowToWindowCoordinates_1)(cIGZWin*, int32_t&, int32_t&) const;
extern "C" PM_WindowToWindowCoordinates_1 volatile pm_WindowToWindowCoordinates_1 = static_cast<PM_WindowToWindowCoordinates_1>(&cIGZWin::WindowToWindowCoordinates);
typedef bool (cIGZWin::*PM_IsPointInWindowScreenCoordinates_1)(int32_t, int32_t) const;
extern "C" PM_IsPointInWindowScreenCoordinates_1 volatile pm_IsPointInWindowScreenCoordinates_1 = static_cast<PM_IsPointInWindowScreenCoordinates_1>(&cIGZWin::IsPointInWindowScreenCoordinates);
typedef uint32_t (cIGZWin::*PM_GetID_1)() const;
extern "C" PM_GetID_1 volatile pm_GetID_1 = static_cast<PM_GetID_1>(&cIGZWin::GetID);
typedef bool (cIGZWin::*PM_SetID_1)(uint32_t);
extern "C" PM_SetID_1 volatile pm_SetID_1 = static_cast<PM_SetID_1>(&cIGZWin::SetID);
typedef uint32_t (cIGZWin::*PM_GetInstanceID_1)() const;
extern "C" PM_GetInstanceID_1 volatile pm_GetInstanceID_1 = static_cast<PM_GetInstanceID_1>(&cIGZWin::GetInstanceID);
typedef bool (cIGZWin::*PM_SetInstanceID_1)(uint32_t);
extern "C" PM_SetInstanceID_1 volatile pm_SetInstanceID_1 = static_cast<PM_SetInstanceID_1>(&cIGZWin::SetInstanceID);
typedef bool (cIGZWin::*PM_GetFlag_1)(cIGZWin::tWinFlag) const;
extern "C" PM_GetFlag_1 volatile pm_GetFlag_1 = static_cast<PM_GetFlag_1>(&cIGZWin::GetFlag);
typedef cIGZWin::tWinFlag (cIGZWin::*PM_SetFlag_1)(cIGZWin::tWinFlag, bool);
extern "C" PM_SetFlag_1 volatile pm_SetFlag_1 = static_cast<PM_SetFlag_1>(&cIGZWin::SetFlag);
typedef bool (cIGZWin::*PM_ShowWindow_1)();
extern "C" PM_ShowWindow_1 volatile pm_ShowWindow_1 = static_cast<PM_ShowWindow_1>(&cIGZWin::ShowWindow);
typedef bool (cIGZWin::*PM_HideWindow_1)();
extern "C" PM_HideWindow_1 volatile pm_HideWindow_1 = static_cast<PM_HideWindow_1>(&cIGZWin::HideWindow);
typedef bool (cIGZWin::*PM_IsVisible_1)() const;
extern "C" PM_IsVisible_1 volatile pm_IsVisible_1 = static_cast<PM_IsVisible_1>(&cIGZWin::IsVisible);
typedef bool (cIGZWin::*PM_IsEnabled_1)() const;
extern "C" PM_IsEnabled_1 volatile pm_IsEnabled_1 = static_cast<PM_IsEnabled_1>(&cIGZWin::IsEnabled);
typedef cIGZString* (cIGZWin::*PM_GetCaption_1)() const;
extern "C" PM_GetCaption_1 volatile pm_GetCaption_1 = static_cast<PM_GetCaption_1>(&cIGZWin::GetCaption);
typedef bool (cIGZWin::*PM_SetCaption_1)(cIGZString const&);
extern "C" PM_SetCaption_1 volatile pm_SetCaption_1 = static_cast<PM_SetCaption_1>(&cIGZWin::SetCaption);
typedef cIGZWinKeyAccelerator* (cIGZWin::*PM_GetKeyboardAccelerator_1)();
extern "C" PM_GetKeyboardAccelerator_1 volatile pm_GetKeyboardAccelerator_1 = static_cast<PM_GetKeyboardAccelerator_1>(&cIGZWin::GetKeyboardAccelerator);
typedef bool (cIGZWin::*PM_SetKeyboardAccelerator_1)(cIGZWinKeyAccelerator*);
extern "C" PM_SetKeyboardAccelerator_1 volatile pm_SetKeyboardAccelerator_1 = static_cast<PM_SetKeyboardAccelerator_1>(&cIGZWin::SetKeyboardAccelerator);
typedef bool (cIGZWin::*PM_AccelerateKeyboardMsg_1)();
extern "C" PM_AccelerateKeyboardMsg_1 volatile pm_AccelerateKeyboardMsg_1 = static_cast<PM_AccelerateKeyboardMsg_1>(&cIGZWin::AccelerateKeyboardMsg);
typedef uint32_t (cIGZWin::*PM_GetKeyEquivalent_1)();
extern "C" PM_GetKeyEquivalent_1 volatile pm_GetKeyEquivalent_1 = static_cast<PM_GetKeyEquivalent_1>(&cIGZWin::GetKeyEquivalent);
typedef bool (cIGZWin::*PM_SetKeyEquivalent_1)(uint32_t);
extern "C" PM_SetKeyEquivalent_1 volatile pm_SetKeyEquivalent_1 = static_cast<PM_SetKeyEquivalent_1>(&cIGZWin::SetKeyEquivalent);
typedef bool (cIGZWin::*PM_CheckKeyEquivalent_1)(uint32_t);
extern "C" PM_CheckKeyEquivalent_1 volatile pm_CheckKeyEquivalent_1 = static_cast<PM_CheckKeyEquivalent_1>(&cIGZWin::CheckKeyEquivalent);
typedef uint32_t (cIGZWin::*PM_MakeKeyEquivalent_1)(uint32_t, uint32_t);
extern "C" PM_MakeKeyEquivalent_1 volatile pm_MakeKeyEquivalent_1 = static_cast<PM_MakeKeyEquivalent_1>(&cIGZWin::MakeKeyEquivalent);
typedef bool (cIGZWin::*PM_IsChildKeyEquivalent_1)(uint32_t, uint32_t);
extern "C" PM_IsChildKeyEquivalent_1 volatile pm_IsChildKeyEquivalent_1 = static_cast<PM_IsChildKeyEquivalent_1>(&cIGZWin::IsChildKeyEquivalent);
typedef bool (cIGZWin::*PM_ProcessCursorMessage_1)(cGZMessage&);
extern "C" PM_ProcessCursorMessage_1 volatile pm_ProcessCursorMessage_1 = static_cast<PM_ProcessCursorMessage_1>(&cIGZWin::ProcessCursorMessage);
typedef bool (cIGZWin::*PM_UpdateCursor_1)();
extern "C" PM_UpdateCursor_1 volatile pm_UpdateCursor_1 = static_cast<PM_UpdateCursor_1>(&cIGZWin::UpdateCursor);
typedef bool (cIGZWin::*PM_SetCursor_1)(cIGZCursor*, bool);
extern "C" PM_SetCursor_1 volatile pm_SetCursor_1 = static_cast<PM_SetCursor_1>(&cIGZWin::SetCursor);
typedef bool (cIGZWin::*PM_SetNotificationTarget_1)(cIGZWin*);
extern "C" PM_SetNotificationTarget_1 volatile pm_SetNotificationTarget_1 = static_cast<PM_SetNotificationTarget_1>(&cIGZWin::SetNotificationTarget);
typedef cIGZWin* (cIGZWin::*PM_GetNotificationTarget_1)();
extern "C" PM_GetNotificationTarget_1 volatile pm_GetNotificationTarget_1 = static_cast<PM_GetNotificationTarget_1>(&cIGZWin::GetNotificationTarget);
typedef bool (cIGZWin::*PM_GZPaint_1)();
extern "C" PM_GZPaint_1 volatile pm_GZPaint_1 = static_cast<PM_GZPaint_1>(&cIGZWin::GZPaint);
typedef bool (cIGZWin::*PM_Plot_1)();
extern "C" PM_Plot_1 volatile pm_Plot_1 = static_cast<PM_Plot_1>(&cIGZWin::Plot);
typedef intptr_t (cIGZWin::*PM_CalcAbsoluteArea_1)();
extern "C" PM_CalcAbsoluteArea_1 volatile pm_CalcAbsoluteArea_1 = static_cast<PM_CalcAbsoluteArea_1>(&cIGZWin::CalcAbsoluteArea);
typedef void (cIGZWin::*PM_InvalidateSelf_1)();
extern "C" PM_InvalidateSelf_1 volatile pm_InvalidateSelf_1 = static_cast<PM_InvalidateSelf_1>(&cIGZWin::InvalidateSelf);
typedef void (cIGZWin::*PM_InvalidateSelfAndParents_1)();
extern "C" PM_InvalidateSelfAndParents_1 volatile pm_InvalidateSelfAndParents_1 = static_cast<PM_InvalidateSelfAndParents_1>(&cIGZWin::InvalidateSelfAndParents);
typedef intptr_t (cIGZWin::*PM_GetDrawContext_1)();
extern "C" PM_GetDrawContext_1 volatile pm_GetDrawContext_1 = static_cast<PM_GetDrawContext_1>(&cIGZWin::GetDrawContext);
typedef intptr_t (cIGZWin::*PM_GetBufferToDrawTo_1)();
extern "C" PM_GetBufferToDrawTo_1 volatile pm_GetBufferToDrawTo_1 = static_cast<PM_GetBufferToDrawTo_1>(&cIGZWin::GetBufferToDrawTo);
typedef void (cIGZWin::*PM_SetBufferToDrawTo_1)();
extern "C" PM_SetBufferToDrawTo_1 volatile pm_SetBufferToDrawTo_1 = static_cast<PM_SetBufferToDrawTo_1>(&cIGZWin::SetBufferToDrawTo);
typedef void (cIGZWin::*PM_SetBufferToDrawToRecursive_1)();
extern "C" PM_SetBufferToDrawToRecursive_1 volatile pm_SetBufferToDrawToRecursive_1 = static_cast<PM_SetBufferToDrawToRecursive_1>(&cIGZWin::SetBufferToDrawToRecursive);
typedef void (cIGZWin::*PM_SetAreaToDrawTo_1)();
extern "C" PM_SetAreaToDrawTo_1 volatile pm_SetAreaToDrawTo_1 = static_cast<PM_SetAreaToDrawTo_1>(&cIGZWin::SetAreaToDrawTo);
typedef void (cIGZWin::*PM_SetAreaToDrawToRecursive_1)();
extern "C" PM_SetAreaToDrawToRecursive_1 volatile pm_SetAreaToDrawToRecursive_1 = static_cast<PM_SetAreaToDrawToRecursive_1>(&cIGZWin::SetAreaToDrawToRecursive);
typedef intptr_t (cIGZWin::*PM_GetAreaToDrawTo_1)();
extern "C" PM_GetAreaToDrawTo_1 volatile pm_GetAreaToDrawTo_1 = static_cast<PM_GetAreaToDrawTo_1>(&cIGZWin::GetAreaToDrawTo);
typedef bool (cIGZWin::*PM_PrivateBuffer_1)(bool);
extern "C" PM_PrivateBuffer_1 volatile pm_PrivateBuffer_1 = static_cast<PM_PrivateBuffer_1>(&cIGZWin::PrivateBuffer);
typedef intptr_t (cIGZWin::*PM_GetPrivateBuffer_1)();
extern "C" PM_GetPrivateBuffer_1 volatile pm_GetPrivateBuffer_1 = static_cast<PM_GetPrivateBuffer_1>(&cIGZWin::GetPrivateBuffer);
typedef bool (cIGZWin::*PM_GetFillColor_1)(cRZColor&);
extern "C" PM_GetFillColor_1 volatile pm_GetFillColor_1 = static_cast<PM_GetFillColor_1>(&cIGZWin::GetFillColor);
typedef uint32_t (cIGZWin::*PM_GetFillColor_2)();
extern "C" PM_GetFillColor_2 volatile pm_GetFillColor_2 = static_cast<PM_GetFillColor_2>(&cIGZWin::GetFillColor);
typedef void (cIGZWin::*PM_GetFillColor_3)(uint8_t&, uint8_t&, uint8_t&);
extern "C" PM_GetFillColor_3 volatile pm_GetFillColor_3 = static_cast<PM_GetFillColor_3>(&cIGZWin::GetFillColor);
typedef bool (cIGZWin::*PM_SetFillColor_1)(cRZColor const&);
extern "C" PM_SetFillColor_1 volatile pm_SetFillColor_1 = static_cast<PM_SetFillColor_1>(&cIGZWin::SetFillColor);
typedef void (cIGZWin::*PM_SetFillColor_2)(uint32_t);
extern "C" PM_SetFillColor_2 volatile pm_SetFillColor_2 = static_cast<PM_SetFillColor_2>(&cIGZWin::SetFillColor);
typedef void (cIGZWin::*PM_SetFillColor_3)(uint8_t, uint8_t, uint8_t);
extern "C" PM_SetFillColor_3 volatile pm_SetFillColor_3 = static_cast<PM_SetFillColor_3>(&cIGZWin::SetFillColor);
typedef bool (cIGZWin::*PM_MakeFillColor_1)(uint8_t, uint8_t, uint8_t);
extern "C" PM_MakeFillColor_1 volatile pm_MakeFillColor_1 = static_cast<PM_MakeFillColor_1>(&cIGZWin::MakeFillColor);
typedef void (cIGZWin::*PM_SetFadeEffectPeriod_1)(int32_t, int32_t);
extern "C" PM_SetFadeEffectPeriod_1 volatile pm_SetFadeEffectPeriod_1 = static_cast<PM_SetFadeEffectPeriod_1>(&cIGZWin::SetFadeEffectPeriod);
typedef void (cIGZWin::*PM_GetFadeEffectPeriod_1)(int32_t&, int32_t&);
extern "C" PM_GetFadeEffectPeriod_1 volatile pm_GetFadeEffectPeriod_1 = static_cast<PM_GetFadeEffectPeriod_1>(&cIGZWin::GetFadeEffectPeriod);
typedef void (cIGZWin::*PM_SetShadeColor_1)(cRZColor const&);
extern "C" PM_SetShadeColor_1 volatile pm_SetShadeColor_1 = static_cast<PM_SetShadeColor_1>(&cIGZWin::SetShadeColor);
typedef void (cIGZWin::*PM_GetShadeColor_1)(cRZColor&);
extern "C" PM_GetShadeColor_1 volatile pm_GetShadeColor_1 = static_cast<PM_GetShadeColor_1>(&cIGZWin::GetShadeColor);
typedef bool (cIGZWin::*PM_GetParam_1)(uint32_t, cIGZVariant**);
extern "C" PM_GetParam_1 volatile pm_GetParam_1 = static_cast<PM_GetParam_1>(&cIGZWin::GetParam);
typedef bool (cIGZWin::*PM_SetParam_1)(uint32_t, cIGZVariant*);
extern "C" PM_SetParam_1 volatile pm_SetParam_1 = static_cast<PM_SetParam_1>(&cIGZWin::SetParam);
typedef bool (cIGZWin::*PM_EnumParams_1)(cIGZWin::EnumParamsCallback, void*);
extern "C" PM_EnumParams_1 volatile pm_EnumParams_1 = static_cast<PM_EnumParams_1>(&cIGZWin::EnumParams);
typedef bool (cIGZWin::*PM_AddMessageFilter_1)(cIGZWinMessageFilter*);
extern "C" PM_AddMessageFilter_1 volatile pm_AddMessageFilter_1 = static_cast<PM_AddMessageFilter_1>(&cIGZWin::AddMessageFilter);
typedef bool (cIGZWin::*PM_RemoveMessageFilter_1)(cIGZWinMessageFilter*);
extern "C" PM_RemoveMessageFilter_1 volatile pm_RemoveMessageFilter_1 = static_cast<PM_RemoveMessageFilter_1>(&cIGZWin::RemoveMessageFilter);
typedef bool (cIGZWin::*PM_SetSize_2)(cRZPoint const&);
extern "C" PM_SetSize_2 volatile pm_SetSize_2 = static_cast<PM_SetSize_2>(&cIGZWin::SetSize);
typedef void (cIGZWin::*PM_CenterWindowInRect_1)(cRZRect const&);
extern "C" PM_CenterWindowInRect_1 volatile pm_CenterWindowInRect_1 = static_cast<PM_CenterWindowInRect_1>(&cIGZWin::CenterWindowInRect);
typedef void (cIGZWin::*PM_CenterWindowInRect_2)(cRZRect*);
extern "C" PM_CenterWindowInRect_2 volatile pm_CenterWindowInRect_2 = static_cast<PM_CenterWindowInRect_2>(&cIGZWin::CenterWindowInRect);
typedef bool (cIGZWin::*PM_IsPointInWindowWindowCoordinates_1)(int32_t, int32_t);
extern "C" PM_IsPointInWindowWindowCoordinates_1 volatile pm_IsPointInWindowWindowCoordinates_1 = static_cast<PM_IsPointInWindowWindowCoordinates_1>(&cIGZWin::IsPointInWindowWindowCoordinates);
typedef bool (cIGZWin::*PM_IsPointInWindowParentCoordinates_1)(int32_t, int32_t);
extern "C" PM_IsPointInWindowParentCoordinates_1 volatile pm_IsPointInWindowParentCoordinates_1 = static_cast<PM_IsPointInWindowParentCoordinates_1>(&cIGZWin::IsPointInWindowParentCoordinates);
typedef bool (cIGZWin::*PM_PlotComposite_1)();
extern "C" PM_PlotComposite_1 volatile pm_PlotComposite_1 = static_cast<PM_PlotComposite_1>(&cIGZWin::PlotComposite);
typedef bool (cIGZWin::*PM_PlotPresent_1)();
extern "C" PM_PlotPresent_1 volatile pm_PlotPresent_1 = static_cast<PM_PlotPresent_1>(&cIGZWin::PlotPresent);
typedef void (cIGZWin::*PM_SetFillColorRGB_1)(uint32_t);
extern "C" PM_SetFillColorRGB_1 volatile pm_SetFillColorRGB_1 = static_cast<PM_SetFillColorRGB_1>(&cIGZWin::SetFillColorRGB);
typedef uint32_t (cIGZWin::*PM_GetFillColorRGB_1)();
extern "C" PM_GetFillColorRGB_1 volatile pm_GetFillColorRGB_1 = static_cast<PM_GetFillColorRGB_1>(&cIGZWin::GetFillColorRGB);
typedef uint32_t (cIGZWin::*PM_ConvertPackedRGBToNative_1)(uint32_t);
extern "C" PM_ConvertPackedRGBToNative_1 volatile pm_ConvertPackedRGBToNative_1 = static_cast<PM_ConvertPackedRGBToNative_1>(&cIGZWin::ConvertPackedRGBToNative);
typedef uint32_t (cIGZWin::*PM_ConvertNativeToPackedRGB_1)(uint32_t);
extern "C" PM_ConvertNativeToPackedRGB_1 volatile pm_ConvertNativeToPackedRGB_1 = static_cast<PM_ConvertNativeToPackedRGB_1>(&cIGZWin::ConvertNativeToPackedRGB);
typedef bool (cIGZWin::*PM_GZOnCharacter_1)(int8_t);
extern "C" PM_GZOnCharacter_1 volatile pm_GZOnCharacter_1 = static_cast<PM_GZOnCharacter_1>(&cIGZWin::GZOnCharacter);
typedef bool (cIGZWin::*PM_GZOnKeyDown_1)(uint32_t, uint32_t);
extern "C" PM_GZOnKeyDown_1 volatile pm_GZOnKeyDown_1 = static_cast<PM_GZOnKeyDown_1>(&cIGZWin::GZOnKeyDown);
typedef bool (cIGZWin::*PM_GZOnKeyUp_1)(uint32_t, uint32_t);
extern "C" PM_GZOnKeyUp_1 volatile pm_GZOnKeyUp_1 = static_cast<PM_GZOnKeyUp_1>(&cIGZWin::GZOnKeyUp);
typedef bool (cIGZWin::*PM_GZOnSetFocus_1)(uint32_t, uint32_t);
extern "C" PM_GZOnSetFocus_1 volatile pm_GZOnSetFocus_1 = static_cast<PM_GZOnSetFocus_1>(&cIGZWin::GZOnSetFocus);
typedef bool (cIGZWin::*PM_GZOnKillFocus_1)(cIGZWin*);
extern "C" PM_GZOnKillFocus_1 volatile pm_GZOnKillFocus_1 = static_cast<PM_GZOnKillFocus_1>(&cIGZWin::GZOnKillFocus);
typedef bool (cIGZWin::*PM_GZOnMouseDownL_1)(int32_t, int32_t, uint32_t);
extern "C" PM_GZOnMouseDownL_1 volatile pm_GZOnMouseDownL_1 = static_cast<PM_GZOnMouseDownL_1>(&cIGZWin::GZOnMouseDownL);
typedef bool (cIGZWin::*PM_GZOnMouseDownR_1)(int32_t, int32_t, uint32_t);
extern "C" PM_GZOnMouseDownR_1 volatile pm_GZOnMouseDownR_1 = static_cast<PM_GZOnMouseDownR_1>(&cIGZWin::GZOnMouseDownR);
typedef bool (cIGZWin::*PM_GZOnMouseUpL_1)(int32_t, int32_t, uint32_t);
extern "C" PM_GZOnMouseUpL_1 volatile pm_GZOnMouseUpL_1 = static_cast<PM_GZOnMouseUpL_1>(&cIGZWin::GZOnMouseUpL);
typedef bool (cIGZWin::*PM_GZOnMouseUpR_1)(int32_t, int32_t, uint32_t);
extern "C" PM_GZOnMouseUpR_1 volatile pm_GZOnMouseUpR_1 = static_cast<PM_GZOnMouseUpR_1>(&cIGZWin::GZOnMouseUpR);
typedef bool (cIGZWin::*PM_GZOnMouseMove_1)(int32_t, int32_t, uint32_t);
extern "C" PM_GZOnMouseMove_1 volatile pm_GZOnMouseMove_1 = static_cast<PM_GZOnMouseMove_1>(&cIGZWin::GZOnMouseMove);
typedef bool (cIGZWin::*PM_GZOnMouseWheel_1)(int32_t, int32_t, uint32_t);
extern "C" PM_GZOnMouseWheel_1 volatile pm_GZOnMouseWheel_1 = static_cast<PM_GZOnMouseWheel_1>(&cIGZWin::GZOnMouseWheel);
typedef bool (cIGZWin::*PM_GZOnCaptureChanged_1)(cIGZWin*, uint32_t, uint32_t, uint32_t);
extern "C" PM_GZOnCaptureChanged_1 volatile pm_GZOnCaptureChanged_1 = static_cast<PM_GZOnCaptureChanged_1>(&cIGZWin::GZOnCaptureChanged);
typedef bool (cIGZWin::*PM_GZOnMouseEnter_1)(uint32_t, uint32_t);
extern "C" PM_GZOnMouseEnter_1 volatile pm_GZOnMouseEnter_1 = static_cast<PM_GZOnMouseEnter_1>(&cIGZWin::GZOnMouseEnter);
typedef bool (cIGZWin::*PM_GZOnMouseExit_1)(uint32_t);
extern "C" PM_GZOnMouseExit_1 volatile pm_GZOnMouseExit_1 = static_cast<PM_GZOnMouseExit_1>(&cIGZWin::GZOnMouseExit);
typedef bool (cIGZWin::*PM_GZOnCommand_1)(uint32_t);
extern "C" PM_GZOnCommand_1 volatile pm_GZOnCommand_1 = static_cast<PM_GZOnCommand_1>(&cIGZWin::GZOnCommand);
typedef bool (cIGZWin::*PM_SendMsg_1)(cIGZWin*, cGZMessage const&);
extern "C" PM_SendMsg_1 volatile pm_SendMsg_1 = static_cast<PM_SendMsg_1>(&cIGZWin::SendMsg);
typedef bool (cIGZWin::*PM_SendMsg_2)(cIGZWin*, uint32_t, uint32_t, uint32_t, uint32_t);
extern "C" PM_SendMsg_2 volatile pm_SendMsg_2 = static_cast<PM_SendMsg_2>(&cIGZWin::SendMsg);
typedef bool (cIGZWin::*PM_PostMsg_1)(cIGZWin*, cGZMessage const&);
extern "C" PM_PostMsg_1 volatile pm_PostMsg_1 = static_cast<PM_PostMsg_1>(&cIGZWin::PostMsg);
typedef bool (cIGZWin::*PM_PostMsg_2)(cIGZWin*, uint32_t, uint32_t, uint32_t, uint32_t);
extern "C" PM_PostMsg_2 volatile pm_PostMsg_2 = static_cast<PM_PostMsg_2>(&cIGZWin::PostMsg);
