# coverage_rederive.py - re-derive the coverage-matrix.md numbers from source data.
#
# READ-ONLY. Opens .UI scripts, UiSpike.cpp, and the art package manifests 'r'.
# Writes nothing except its own stdout (and --json to a path you name).
#
# The claim under test (tools\uimap\coverage-matrix.md:2, "Denominator ladder"):
#   "339 .ui files -> 282 layout scripts -> 330 depth-0 roots,
#    329 with a nonzero id, 117 distinct (116 nonzero + the one id-less root)"
#
# Usage:  python coverage_rederive.py [--json out.json]
#         python coverage_rederive.py --selftest    (negative control, see below)
# Exit:   0 = every hard expectation held.  1 = at least one FAILED (loudly).
#         --selftest inverts that: 0 means the net correctly REJECTED a
#         deliberately broken parser.
#
# ---------------------------------------------------------------------------
# 2026-08-03 - TASK #99 - THE BUG THIS FILE USED TO HAVE, AND WHY IT MATTERED
# ---------------------------------------------------------------------------
# parse_script() used to `break` at the FIRST <LEGACY> in every file:
#
#       for ln in lines:
#           if RE_LEGACY.search(ln):
#               ...
#               break            # <-- one root per file. WRONG.
#
# 21 of the 282 layout scripts declare more than one top-level root, so the
# tool silently dropped 48 roots. It then printed "282 roots / 281 with id /
# 91 distinct" and a Section 5 ratio of 241/281 = 85.8%, and that 85.8% was
# quoted elsewhere as an INDEPENDENT CHECK on coverage-matrix.md. It was not
# independent and it was not right: the doc was correct, the tool was wrong.
#
# The miscount is the symptom. The ACTUAL bug is that a broken parser produced
# a plausible smaller number and exited 0. Everything below the parser now
# exists to stop that happening again:
#   * hard expectations (EXPECT) that FAIL the run, not a warning;
#   * a POSITIVE CONTROL that proves the parser CAN see a second root before
#     any "no extra roots here" is allowed to count as evidence;
#   * SKIPPED checks counted and printed separately - a skip is never a pass.
#
# ---------------------------------------------------------------------------
# 2026-08-03 - TASK #99, SECOND DEFECT - THE CORPUS FILTER ALSO DROPPED FILES
# ---------------------------------------------------------------------------
# !! HISTORICAL NOTE, 2026-08-03 (later, same day). The text below was written
# !! as though this second fix had LANDED. IT HAD NOT. Someone wrote the
# !! diagnosis, added the BANNER_PREFIX_CI and BOMS constants, and wrote
# !! "See accounting() below" - then never wired any of it up. Measured state
# !! at the start of this task:
# !!     * parse_script() line ~195 still read
# !!           if not text.lstrip().startswith(BANNER): return None
# !!       i.e. the exact-string, BOM-blind, case-sensitive test.
# !!     * BANNER_PREFIX_CI was referenced NOWHERE except its own definition.
# !!     * BOMS was referenced NOWHERE except its own definition.
# !!     * accounting() DID NOT EXIST. `grep -n accounting` returned exactly
# !!       one hit: the comment promising it.
# !! And the run still printed OVERALL: PASS, because EXPECT had been frozen to
# !! the POST-DROP numbers (282 / 330 / 329 / 117). The expectations agreed
# !! with the bug. That is the same failure #99 was filed for, one level up:
# !! a green gate whose green was guaranteed by construction.
# !! OUR OWN COMMENTS AND NOTES LIE. The diagnosis below is CORRECT and is
# !! kept verbatim; it is now actually IMPLEMENTED (see classify_file() and
# !! accounting()). EXPECT has been re-derived against the corrected corpus.
#
# The root-enumeration fix above was real, but it fixed the numerator side of
# the parser only. The DENOMINATOR was still wrong, for a different reason:
#
#       BANNER = "# Generated by UI editor"
#       if not text.lstrip().startswith(BANNER):
#           return None                      # <-- silently NOT a layout script
#
# That single test threw away 8 real layout scripts holding 8 depth-0 roots,
# by two separate mechanisms, neither of which left any trace in the output:
#
#   (a) UTF-8 BOM.  tools\uiscripts\extracted\T-00000000_G-96a006b0_I-ca551016.ui
#       begins EF BB BF then the exact banner. Decoded latin-1 that is the
#       three characters 'i>>?' - str.lstrip() strips WHITESPACE, not a BOM, so
#       startswith() was False. 1 game script, 1 root (0x0A592004), dropped.
#
#   (b) Banner variant + case.  The 7 plugin scripts extracted by the other
#       tool begin "# Generated by UIEditor - Reader 1.0.0" - "UIEditor" not
#       "UI editor". startswith() is case-sensitive and exact. 7 plugin
#       scripts, 7 roots, dropped. That is why Section 1 used to print
#       "plugin 2" when tools\uiscripts\extracted-plugins holds 9 .ui files.
#
# Both were INVISIBLE: a dropped file was indistinguishable from a file that
# genuinely is not a layout script, because nothing counted the two buckets
# against the enumerated total. The corpus filter is now DOUBLE-CLASSIFIED
# (banner test AND content test) and the two must agree on every file; a
# disagreement is a named FAIL, never a silent drop. See accounting() below.
#
# The 49 remaining non-layout .ui files are REAL non-layouts, measured not
# assumed: 45 are binary (magic 'AB\x09\x00', 0.4-1.6 MB), 3 are INI text
# (';' / '[Config]' - e.g. network path-remapping parameters), 1 is a ';'
# comment block. NONE of the 49 contains the substring "<LEGACY" anywhere.
# That is the positive control for the exclusion: the filter is not hiding a
# layout script inside the excluded bucket, and the run asserts it every time.
#
# ---------------------------------------------------------------------------
# 2026-08-03 - TASK #99, THIRD DEFECT - TWO RECONCILIATIONS THAT COULD NOT FAIL
# ---------------------------------------------------------------------------
# The two fixes above are REAL and are still in force; the root/corpus numbers
# they produce (338 / 337 / 118) were re-confirmed today by a structurally
# independent parser. What was NOT true is the claim, made by this file's own
# accounting(), that four "independent reconciliations" were guarding them.
# Two of the four were GREEN BY CONSTRUCTION and could never report a negative:
#
#   A. FILE CONSERVATION compared
#           accounted = len(layout)+len(non-layout)+len(disagree)+len(unreadable)
#      against len(all_files). But `records` is built as exactly one
#      classify_file() call per entry of all_files, and classify_file() always
#      returns exactly one of those four verdicts. So accounted == len(all_files)
#      is an ARITHMETIC IDENTITY. The `missing` branch below it was dead code.
#      It also could not see the real drop mode, which is UPSTREAM: script_files()
#      returns [] for a directory that does not exist, and all_files and records
#      then agree on the same truncated corpus.
#
#   C. ROOT CONSERVATION compared `carried` (roots stored by parse_script) with
#      `fresh` (roots from "a fresh independent pass"). Both were
#      enumerate_roots(text) - THE SAME PURE FUNCTION ON THE SAME STRING. Its
#      own comment one function up ("ONE enumerator, shared with CLASSIFIER B")
#      is what makes the comparison a tautology. It caught the selftest only
#      because that injection patched the parse_script WRAPPER; a defect inside
#      the enumerator itself was invisible to it.
#
# MEASURED, not argued. Injecting `roots[:1]` inside enumerate_roots() and
# re-running printed, with 48 roots being dropped:
#       [OK ] FILE CONSERVATION: every enumerated file is accounted for.
#       depth-0 roots carried by census      : 290
#       depth-0 roots found by a fresh pass  : 290
#       [OK ] ROOT CONSERVATION: census carries every root found.
# Both "conservation" checks reported OK on a corpus that had just lost 48 of
# its 338 roots. (The RUN still failed - EXPECT, the positive control and the
# coverage floors all fired - so the headline numbers were never at risk. But
# two of the four named guards were decorative, and the file said otherwise.)
#
# Both are now reconciled against genuinely INDEPENDENT sources - independent
# in the sense that matters, DIFFERENT FAILURE MODES, not merely a second call:
#   * A -> a recursive os.walk of the script roots (the census uses a flat
#          os.listdir), plus the extractor's own extract-manifest.csv, plus an
#          explicit non-empty test on each source directory.
#   * C -> enumerate_roots_streamwise(), a second root enumerator that shares
#          no code with the first: it tokenises on '<' outside quotes and never
#          splits the file into lines at all, so line-anchored regexes,
#          _blank_quoted() and splitlines() cannot fail it the same way.
# selftest cases 3 and 4 inject defects that ONLY these two can catch.
# ---------------------------------------------------------------------------

import csv, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))

SCRIPTS_GAME    = os.path.join(REPO, "tools", "uiscripts", "extracted")
SCRIPTS_PLUGINS = os.path.join(REPO, "tools", "uiscripts", "extracted-plugins")
UISPIKE         = os.path.join(REPO, "src", "UiSpike.cpp")

# A layout script is a TEXT .UI written by one of the UI-editor/extractor tools.
# TWO banner spellings exist in this corpus and BOTH are real (see header):
#   "# Generated by UI editor"                283 files (game + 2 plugin)
#   "# Generated by UIEditor - Reader 1.0.0"    7 files (plugin extractor)
# Matching is done on a case-folded prefix so a third variant from the same
# family still classifies; anything further from the family trips the
# banner-vs-content disagreement check instead of vanishing.
BANNER = "# Generated by UI editor"            # kept: the historical exact string
BANNER_PREFIX_CI = "# generated by ui"         # what the classifier actually uses

# Byte-order marks seen through a latin-1 decode. str.lstrip() does NOT strip
# these - that is defect (a) in the header. Longest first so UTF-32 wins over
# UTF-16 on a prefix match.
BOMS = ("\xff\xfe\x00\x00", "\x00\x00\xfe\xff",   # UTF-32 LE / BE
        "\xef\xbb\xbf",                           # UTF-8
        "\xff\xfe", "\xfe\xff",                   # UTF-16 LE / BE
        "﻿")                                 # already-decoded ZWNBSP

RE_ID   = re.compile(r"\bid=0x([0-9a-fA-F]{1,8})")
RE_AREA = re.compile(r"\barea=\((-?\d+),(-?\d+),(-?\d+),(-?\d+)\)")
RE_IMAGE  = re.compile(r"\bimage=\{([0-9a-fA-F]+),([0-9a-fA-F]+)\}")

# Structure tags. Anchored to the start of the line: in this format every tag
# opens its own line. Quoted attribute values are blanked before matching
# (107 elements in the corpus carry newlines inside quoted values and 84
# quoted values contain a literal '>', so a naive scan can be fooled).
RE_LEGACY_LINE   = re.compile(r"^\s*<LEGACY\b")
RE_CHILDREN_OPEN = re.compile(r"^\s*<CHILDREN\s*>")
RE_CHILDREN_END  = re.compile(r"^\s*</CHILDREN\s*>")

# Legacy loose matcher, kept only for the node census (counts <LEGACY> anywhere).
RE_LEGACY = re.compile(r"<LEGACY\b")

# ---------------------------------------------------------------------------
# HARD EXPECTATIONS. Every one of these is a MEASURED number, re-derived today
# by a depth-tracking count run three ways (line-anchored, unanchored, and
# quote-aware) over the same corpus; all three agreed. If the corpus legitimately
# changes, update these AND say so in coverage-matrix.md - do not delete them.
# ---------------------------------------------------------------------------
EXPECT = {
    "ui_files":                339,   # .ui on disk (game + plugins)
    "layout_scripts":          290,   # of those, DOUBLE-CLASSIFIED text layouts
    "depth0_roots":            338,   # top-level <LEGACY> across all layouts
    "roots_with_nonzero_id":   337,   # ... of which carry id=0x...
    "distinct_root_ids":       118,   # 117 nonzero + 1 bucket for the id-less root
    "distinct_nonzero_root_ids": 117,
    "multi_root_scripts":       21,   # scripts declaring >1 top-level root
    "extra_roots":              48,   # roots beyond one-per-script
    # coverage-matrix.md section 3.5 "My depth-aware count: 32 root ids built by
    # more than one distinct script instance". This tool now reproduces that
    # independently - it could NOT before #99 (it printed 27).
    "stale_copy_root_ids":      32,
    "non_layout_files":         49,   # the measured non-layout bucket
}

# The pre-2026-08-03 EXPECT block, kept so the size and DIRECTION of the
# instrument's error stays on the record instead of being quietly overwritten.
# These were frozen to the POST-DROP corpus, so the gate agreed with the bug.
EXPECT_BEFORE_CORPUS_FIX = {
    "layout_scripts":          282,   # -8  : 1 BOM'd game script + 7 plugin scripts
    "depth0_roots":            330,   # -8
    "roots_with_nonzero_id":   329,   # -8
    "distinct_root_ids":       117,   # -1  : only 0x0A592004 was wholly unseen
    "distinct_nonzero_root_ids": 116, # -1
}

# ---------------------------------------------------------------------------
# COVERAGE FLOORS. Without these, section 5 is a number nobody is watching:
# a genuine regression would print a smaller percentage and still exit 0.
# A floor turns a regression into a FAIL. It is a FLOOR, not an equality, so
# real improvement does not trip it - but it must then be RAISED, and the run
# says so out loud when coverage exceeds the floor.
#
# MEASURED 2026-08-03 against the CORRECTED 337-root denominator.
# ---------------------------------------------------------------------------
COVERAGE_FLOOR = {
    "roots_root_id_named":   293,   # 293/337 = 86.9%
    "roots_any_id_named":    295,   # 295/337 = 87.5%
    # v2.65.0 (#54): 79 -> 83. Three Mode C roots (0x0A41C7B2/B3, 0x27DF05BF)
    # entered kNeverScaleIds. NOTE the denominator is misleading and the #54
    # census says why: of the 38 roots this metric counted as "uncovered",
    # 20 are SC4's own DEVELOPER TOOLS (Script Console / Breakpoints / Call
    # Stack / Variables / Script View / Lot Configuration Editor / Select
    # Prop|Building|Flora Families / Set Compatibilities / Configure Columns /
    # Simulator Control), 8 are scaled in DATA where this grep cannot see them,
    # 3 are MEASURED ABSENT from the shipping image, and 2 more are code-created
    # or dev twins. In-scope coverage is ~87/92. Do not read 70.9% as "29% of
    # the UI is broken" - most of that denominator must NEVER be scaled.
    "distinct_root_ids_named": 83,  #  83/117 = 70.9%
}

# NOTE (discrepancy, NOT forced into agreement): coverage-matrix.md section 2
# says "22 scripts contain more than one top-level root (49 extra roots)".
# This run measures 21 / 48. 330 roots - 282 layout scripts = 48 extra, so 49
# is only reachable if some layout script declares ZERO top-level roots; this
# tool checks that directly (zero_root_scripts below) and measures none.
# The headline ladder (330 / 329 / 117) reproduces exactly. Reported, not edited.
DOC_MULTI_ROOT_SCRIPTS = 22
DOC_EXTRA_ROOTS = 49

# POSITIVE CONTROL. Before any "this script has only one root" is allowed to
# count as evidence, the parser must demonstrate on a known-multi-root file
# that it CAN see roots 2..N. This is the exact check the old parser would
# have failed. NULL IS NOT EVIDENCE.
POSITIVE_CONTROL = ("T-00000000_G-96a006b0_I-aa1f1f57.ui", 9)


def script_files(d):
    if not os.path.isdir(d):
        return []
    return [os.path.join(d, f) for f in sorted(os.listdir(d)) if f.lower().endswith(".ui")]


def _blank_quoted(text):
    """Blank out the inside of double-quoted values, preserving newlines and
    line lengths, so tag matching cannot be fooled by '>' or '<LEGACY' text
    sitting inside a tiptext= string."""
    out = []
    inq = False
    for ch in text:
        if ch == '"':
            inq = not inq
            out.append(' ')
        elif ch == '\n':
            out.append(ch)
        else:
            out.append(' ' if inq else ch)
    return ''.join(out)


def strip_bom(text):
    """Remove any leading byte-order mark(s) seen through the latin-1 decode.
    str.lstrip() strips WHITESPACE only and will NOT remove these - that was
    defect (a). Loops because a file can carry a decoded ZWNBSP after a raw BOM."""
    t = text
    while True:
        for b in BOMS:
            if t.startswith(b):
                t = t[len(b):]
                break
        else:
            return t


def banner_ok(text):
    """CLASSIFIER A - provenance. Case-folded, BOM-tolerant prefix match against
    the UI-editor/extractor banner family."""
    return strip_bom(text).lstrip().lower().startswith(BANNER_PREFIX_CI)


def enumerate_roots(text):
    """The depth-0 root enumerator, factored out so CLASSIFIER B and the
    root-accounting cross-check can use the SAME code path the census uses.
    Returns (roots, final_depth, min_depth)."""
    scan_lines = _blank_quoted(text).splitlines()
    raw_lines = text.splitlines()
    roots = []
    cur = None
    depth = 0
    min_depth = 0
    for i, sline in enumerate(scan_lines):
        rline = raw_lines[i] if i < len(raw_lines) else ""
        if RE_LEGACY_LINE.search(sline):
            if depth == 0:
                m = RE_ID.search(rline)
                a = RE_AREA.search(rline)
                cur = dict(id=(int(m.group(1), 16) if m else 0),
                           area=(tuple(int(x) for x in a.groups()) if a else None),
                           ids=set(), images=set(), nodes=0)
                roots.append(cur)
            if cur is not None:
                cur["nodes"] += 1
                for m in RE_ID.finditer(rline):
                    cur["ids"].add(int(m.group(1), 16))
                for m in RE_IMAGE.finditer(rline):
                    cur["images"].add((int(m.group(1), 16), int(m.group(2), 16)))
        # structure tags sit on their own lines; close before open
        if RE_CHILDREN_END.search(sline):
            depth -= 1
        elif RE_CHILDREN_OPEN.search(sline):
            depth += 1
        min_depth = min(min_depth, depth)
    return roots, depth, min_depth


def enumerate_roots_streamwise(text):
    """SECOND, INDEPENDENT depth-0 root enumerator. Shares NO code with
    enumerate_roots() - that is the entire point (see header, third defect).

    Different failure modes on purpose:
      * never calls splitlines(), so \\r / \\x0b / \\x0c / \\x85 inside a value
        cannot desynchronise it;
      * never calls _blank_quoted(), so a quote-state bug there cannot fool
        both enumerators the same way;
      * uses no ^-anchored regex, so it does not care whether an element
        starts its own line.
    It walks the character stream, treats every '<' seen OUTSIDE double quotes
    as the start of an element, and tracks <CHILDREN> depth over that stream.

    Returns a list of root ids (0 for a root with no id=), in document order.
    """
    ids = []
    depth = 0
    inq = False
    i = 0
    n = len(text)
    start = None
    tag = None

    def close(body):
        nonlocal depth
        if tag == "LEGACY":
            if depth == 0:
                m = RE_ID.search(body)
                ids.append(int(m.group(1), 16) if m else 0)
        elif tag == "CHILDREN":
            depth += 1
        elif tag == "/CHILDREN":
            depth -= 1

    while i < n:
        ch = text[i]
        if ch == '"':
            inq = not inq
        elif ch == '<' and not inq:
            if start is not None:
                close(text[start:i])
            m = re.match(r"</?([A-Za-z_]+)", text[i:])
            if m:
                tag = ("/" if text[i + 1:i + 2] == "/" else "") + m.group(1)
            else:
                tag = "?"
            start = i
        i += 1
    if start is not None:
        close(text[start:])
    return ids


def content_ok(text):
    """CLASSIFIER B - content. Independent of the banner: does this file
    actually declare at least one depth-0 <LEGACY> root?"""
    return len(enumerate_roots(text)[0]) > 0


def classify_file(path):
    """DOUBLE CLASSIFICATION. Returns a record for EVERY enumerated file, so
    nothing can leave the corpus without being counted somewhere.

    verdict is one of:
      'layout'     banner AND content agree: yes
      'non-layout' banner AND content agree: no
      'disagree'   the two classifiers DISAGREE -> a named FAIL, never a drop
      'unreadable' the file could not be decoded -> a named FAIL, never a drop
    """
    try:
        with open(path, "r", encoding="latin-1") as f:
            text = f.read()
    except Exception as e:
        return dict(path=path, base=os.path.basename(path), verdict="unreadable",
                    reason=repr(e), text=None, banner=None, content=None)
    b = banner_ok(text)
    c = content_ok(text)
    if b and c:
        v = "layout"
    elif not b and not c:
        v = "non-layout"
    else:
        v = "disagree"
    return dict(path=path, base=os.path.basename(path), verdict=v,
                reason=None, text=text, banner=b, content=c)


def parse_script(path):
    """Parse one .UI layout script.

    Returns None if the file is not a layout script (see classify_file).

    Enumerates ALL depth-0 <LEGACY> roots by tracking nesting depth through
    <CHILDREN> / </CHILDREN>. Each root carries its own subtree's ids, images
    and node count, so a multi-root script is no longer collapsed to its first
    root (task #99).
    """
    rec = classify_file(path)
    if rec["verdict"] != "layout":
        return None
    text = rec["text"]

    raw_lines = text.splitlines()
    # ONE enumerator, shared with CLASSIFIER B. Two copies of this loop would
    # be two things that can disagree silently - exactly the failure mode #99
    # is about.
    roots, depth, min_depth = enumerate_roots(text)

    # file-wide sets (unchanged semantics: every id / image anywhere in the file)
    ids = set()
    for ln in raw_lines:
        if RE_LEGACY.search(ln):
            for m in RE_ID.finditer(ln):
                ids.add(int(m.group(1), 16))
    imgs = set()
    for m in RE_IMAGE.finditer(text):
        imgs.add((int(m.group(1), 16), int(m.group(2), 16)))

    base = os.path.basename(path)
    # T-00000000_G-96a006b0_I-2bc90671.ui
    parts = base[:-3].split("_")
    grp = parts[1][2:] if len(parts) > 1 else "?"
    inst = parts[2][2:] if len(parts) > 2 else "?"
    return dict(path=path, base=base, group=grp, inst=inst,
                roots=roots,
                balanced=(depth == 0 and min_depth >= 0),
                final_depth=depth, min_depth=min_depth,
                ids=ids, node_count=sum(1 for ln in raw_lines if RE_LEGACY.search(ln)),
                images=imgs)


MANIFEST = os.path.join(SCRIPTS_GAME, "extract-manifest.csv")


def independent_file_census():
    """INDEPENDENT enumeration of the .ui corpus, for reconciliation against the
    census's own script_files() list.

    script_files() uses a FLAT os.listdir() per directory and returns [] for a
    directory that does not exist. Both of those are silent-drop modes, and
    neither can be seen by comparing all_files against anything derived FROM
    all_files. So this walks the tree a different way and also consults a source
    that does not live in the same place at all: the extractor's own
    extract-manifest.csv, which records what the DBPF extraction produced.

    Returns (walked_set, manifest_set_or_None, empty_dirs, missing_dirs).
    """
    walked = set()
    empty_dirs = []
    missing_dirs = []
    for d in (SCRIPTS_GAME, SCRIPTS_PLUGINS):
        if not os.path.isdir(d):
            missing_dirs.append(d)
            continue
        found = 0
        for root, _dirs, files in os.walk(d):
            for f in files:
                if f.lower().endswith(".ui"):
                    walked.add(os.path.normcase(os.path.abspath(
                        os.path.join(root, f))))
                    found += 1
        if found == 0:
            empty_dirs.append(d)

    manifest = None
    if os.path.isfile(MANIFEST):
        manifest = set()
        with open(MANIFEST, "r", encoding="latin-1", newline="") as f:
            for row in csv.DictReader(f):
                name = (row.get("File") or "").strip()
                if not name:
                    continue
                # the extractor writes .png names; they are renamed .ui on disk
                stem = os.path.splitext(name)[0]
                manifest.add(os.path.normcase(os.path.abspath(
                    os.path.join(SCRIPTS_GAME, stem + ".ui"))))
    return walked, manifest, empty_dirs, missing_dirs


def accounting(all_files, records, parsed):
    """THE SELF-CHECK #99 ASKED FOR. Every enumerated file, and every depth-0
    root, must be ACCOUNTED FOR. Returns (fail_list, info_dict).

    Four reconciliations. Each is checked against a source with a DIFFERENT
    failure mode, so each can actually report a NEGATIVE. Re-deriving a number
    from the same data by the same code and finding it equal proves nothing -
    two of these used to do exactly that (see header, third defect).

      A. FILE CONSERVATION.  the census's flat os.listdir is reconciled against
                             (a) a recursive os.walk, (b) the extractor's own
                             extract-manifest.csv, and (c) an explicit
                             exists/non-empty test on each source directory -
                             the silent-drop mode script_files() has built in.
                             Any delta is listed BY NAME.
                             The verdict partition (layout+non-layout+disagree+
                             unreadable == enumerated) is an IDENTITY and is
                             printed as bookkeeping, not asserted as a check.
      B. CLASSIFIER AGREEMENT.  banner-provenance and content-structure must
                             agree on every file. A disagreement is the exact
                             shape of both #99 drops (BOM / banner variant),
                             and is a FAIL, never a silent exclusion.
      C. ROOT CONSERVATION.  the roots the census carries must equal, ID FOR ID,
                             the roots found by enumerate_roots_streamwise() -
                             a second parser sharing no code with the first
                             (no splitlines, no _blank_quoted, no ^-anchors).
                             Catches a drop inside the enumerator itself, which
                             the old same-function comparison could not.
      D. EXCLUSION POSITIVE CONTROL.  no file classified 'non-layout' may
                             contain the substring '<LEGACY' anywhere. Without
                             this, "the excluded bucket holds no layouts" is an
                             UNPROVEN NULL. NULL IS NOT EVIDENCE.
    """
    fails = []
    info = {}

    by_verdict = {}
    for r in records:
        by_verdict.setdefault(r["verdict"], []).append(r)
    layout     = by_verdict.get("layout", [])
    nonlayout  = by_verdict.get("non-layout", [])
    disagree   = by_verdict.get("disagree", [])
    unreadable = by_verdict.get("unreadable", [])

    print()
    print("== SECTION 0: CORPUS ACCOUNTING (enumerated == accounted-for) ==")
    print("  enumerated .ui files        : %d" % len(all_files))
    print("    classified 'layout'       : %d" % len(layout))
    print("    classified 'non-layout'   : %d" % len(nonlayout))
    print("    CLASSIFIER DISAGREEMENT   : %d" % len(disagree))
    print("    unreadable                : %d" % len(unreadable))

    # ---- A. file conservation ----
    # The verdict partition is an ARITHMETIC IDENTITY (one record per file, one
    # verdict per record), so it is printed as bookkeeping and NOT counted as a
    # check. Asserting it would be a guaranteed-green gate - the exact thing #99
    # is about. The real reconciliation is against INDEPENDENT enumerations.
    accounted = len(layout) + len(nonlayout) + len(disagree) + len(unreadable)
    print("  accounted-for total         : %d  (identity, not a check)" % accounted)

    walked, manifest, empty_dirs, missing_dirs = independent_file_census()
    census = set(os.path.normcase(os.path.abspath(f)) for f in all_files)

    # A0. a source directory that vanished is the silent-drop mode script_files()
    #     has by construction (`if not os.path.isdir(d): return []`).
    for d in missing_dirs:
        print("  [FAIL] SOURCE DIRECTORY MISSING: %s" % d)
        print("         script_files() returns [] for this silently.")
        fails.append(("source dir missing", d, "absent"))
    for d in empty_dirs:
        print("  [FAIL] SOURCE DIRECTORY EMPTY: %s (0 .ui files)" % d)
        fails.append(("source dir empty", d, 0))

    # A1. flat listdir (census) vs recursive walk (independent)
    print("  independent recursive walk  : %d .ui files" % len(walked))
    only_walk = sorted(walked - census)
    only_census = sorted(census - walked)
    if only_walk or only_census:
        print("  [FAIL] FILE CONSERVATION: census %d vs walk %d (delta %+d)"
              % (len(census), len(walked), len(walked) - len(census)))
        for f in only_walk[:40]:
            print("         ON DISK, NOT IN CENSUS: %s" % f)
        for f in only_census[:40]:
            print("         IN CENSUS, NOT ON DISK: %s" % f)
        fails.append(("file conservation (walk)", len(walked), len(census)))
    else:
        print("  [OK ] FILE CONSERVATION: census == independent recursive walk.")

    # A2. reconcile against the extractor's own manifest - a source that does
    #     not derive from this directory listing at all.
    if manifest is None:
        print("  [SKIP] extract-manifest.csv absent - manifest reconciliation"
              " NOT performed.")
        info["manifest_checked"] = False
    else:
        info["manifest_checked"] = True
        lost = sorted(manifest - census)
        extra = sorted(census - manifest - set(
            os.path.normcase(os.path.abspath(f))
            for f in script_files(SCRIPTS_PLUGINS)))
        print("  extract-manifest.csv rows   : %d" % len(manifest))
        if lost or extra:
            print("  [FAIL] MANIFEST RECONCILIATION: %d extracted file(s) missing"
                  " from the census, %d census file(s) not in the manifest"
                  % (len(lost), len(extra)))
            for f in lost[:40]:
                print("         EXTRACTED BUT GONE: %s" % os.path.basename(f))
            for f in extra[:40]:
                print("         UNEXPLAINED       : %s" % os.path.basename(f))
            fails.append(("manifest reconciliation", len(manifest), len(lost)))
        else:
            print("  [OK ] MANIFEST RECONCILIATION: every extracted .ui is in"
                  " the census.")

    # ---- B. classifier agreement ----
    if disagree:
        print("  [FAIL] CLASSIFIER DISAGREEMENT on %d file(s). These are NOT"
              % len(disagree))
        print("         dropped - they are named here so the count cannot lie:")
        for r in disagree:
            print("         %-46s banner=%s content=%s" %
                  (r["base"], r["banner"], r["content"]))
            print("            first 48 bytes: %r"
                  % r["text"][:48].encode("latin-1", "replace"))
        print("         banner=False/content=True  -> banner family widened?"
              " (this was the #99 BOM + 'UIEditor' drop)")
        print("         banner=True /content=False -> a layout script declaring"
              " ZERO depth-0 roots; investigate before excluding.")
        fails.append(("classifier agreement", 0, len(disagree)))
    else:
        print("  [OK ] CLASSIFIER AGREEMENT: banner and content agree on all %d"
              " files." % len(all_files))

    if unreadable:
        for r in unreadable:
            print("  [FAIL] UNREADABLE: %s  %s" % (r["base"], r["reason"]))
        fails.append(("unreadable files", 0, len(unreadable)))

    # ---- C. root conservation ----
    # Reconciled against enumerate_roots_streamwise(), which shares no code with
    # the line-based enumerator. Re-calling enumerate_roots() here (what this
    # check used to do) compares a pure function to itself and can never fail.
    carried = sum(len(p["roots"]) for p in parsed)
    fresh = 0
    per_file_delta = []
    by_path = {p["path"]: p for p in parsed}
    for r in layout:
        stream_ids = enumerate_roots_streamwise(r["text"])
        fresh += len(stream_ids)
        p = by_path.get(r["path"])
        got_ids = [x["id"] for x in p["roots"]] if p else []
        if got_ids != stream_ids:
            per_file_delta.append((r["base"], len(stream_ids), len(got_ids),
                                   got_ids, stream_ids))
    print("  depth-0 roots carried by census          : %d" % carried)
    print("  depth-0 roots found by the STREAM parser : %d" % fresh)
    if carried != fresh or per_file_delta:
        print("  [FAIL] ROOT CONSERVATION: %d carried vs %d found by an"
              " independent parser (delta %+d), %d file(s) disagree"
              % (carried, fresh, carried - fresh, len(per_file_delta)))
        for (b, want, got, gi, si) in per_file_delta[:40]:
            print("         %-46s stream=%d carried=%d" % (b, want, got))
            print("            carried ids: %s"
                  % " ".join("0x%08X" % x for x in gi[:12]))
            print("            stream  ids: %s"
                  % " ".join("0x%08X" % x for x in si[:12]))
        fails.append(("root conservation", fresh, carried))
    else:
        print("  [OK ] ROOT CONSERVATION: two independent parsers agree on"
              " every root id in every file.")

    # ---- D. exclusion positive control ----
    leaked = [r for r in nonlayout if "<LEGACY" in r["text"]]
    print("  excluded files containing '<LEGACY'  : %d  (must be 0)" % len(leaked))
    if leaked:
        print("  [FAIL] EXCLUSION POSITIVE CONTROL: the excluded bucket is"
              " hiding layout content.")
        for r in leaked[:40]:
            print("         %s" % r["base"])
        fails.append(("exclusion positive control", 0, len(leaked)))
    else:
        print("  [OK ] EXCLUSION POSITIVE CONTROL: no excluded file contains"
              " '<LEGACY'.")
        print("         (Positive control for THIS control: the check demonstrably")
        print("          CAN fire - before the #99 corpus fix it fired on 8 files.)")

    info["n_layout"] = len(layout)
    info["n_nonlayout"] = len(nonlayout)
    info["n_disagree"] = len(disagree)
    info["n_unreadable"] = len(unreadable)
    info["roots_carried"] = carried
    info["roots_stream"] = fresh
    info["n_walked"] = len(walked)
    return fails, info


def cpp_id_list(text, name):
    """Extract the hex ids out of `const uint32_t <name>[] = { ... };`."""
    i = text.find(name + "[]")
    if i < 0:
        return None, None
    j = text.find("{", i)
    # brace-match
    depth = 0
    k = j
    while k < len(text):
        if text[k] == "{":
            depth += 1
        elif text[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    body = text[j:k]
    # strip // and /* */ comments so commented-out ids do not count
    body_nc = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body_nc = re.sub(r"//[^\n]*", "", body_nc)
    ids = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{6,8})\b", body_nc)]
    line = text[:i].count("\n") + 1
    return ids, line


def main():
    out_json = None
    if "--json" in sys.argv:
        out_json = sys.argv[sys.argv.index("--json") + 1]

    checks = 0
    fails = []          # (label, expected, measured) - each one FAILS the run
    skips = []          # (label, reason, what would clear it) - never a pass

    def expect(label, key, measured):
        """Hard expectation. Records a FAIL; does not raise, so one run reports
        every divergence rather than only the first."""
        want = EXPECT[key]
        ok = (measured == want)
        print("  [%s] %-32s expected %-5d measured %d"
              % ("OK " if ok else "FAIL", label, want, measured))
        if not ok:
            fails.append((label, want, measured))
        return ok

    # ---------- section 1: the script corpus ----------
    game_files = script_files(SCRIPTS_GAME)
    plug_files = script_files(SCRIPTS_PLUGINS)
    all_files = game_files + plug_files
    # classify EVERY file once, keep the record, then parse only the layouts.
    records = [classify_file(f) for f in all_files]
    parsed = [p for p in (parse_script(f) for f in all_files) if p]

    acc_fails, acc_info = accounting(all_files, records, parsed)
    fails.extend(acc_fails)
    # A0 dirs-exist, A1 walk, A2 manifest, B classifier, C root, D exclusion
    checks += 6
    print()
    # NOTE: SCRIPTS_PLUGINS starts with SCRIPTS_GAME as a string prefix
    # ("extracted" / "extracted-plugins"), so a startswith() partition
    # miscounts every plugin script as a game script. Partition by the set of
    # files each directory actually yielded instead.
    plug_paths = set(plug_files)
    game = [p for p in parsed if p["path"] not in plug_paths]
    plug = [p for p in parsed if p["path"] in plug_paths]

    by_group = {}
    for p in parsed:
        by_group.setdefault(p["group"], []).append(p)

    print("== SECTION 1: script corpus ==")
    print("  .ui files on disk           : %d (game %d + plugins %d)"
          % (len(all_files), len(game_files), len(plug_files)))
    print("  LAYOUT scripts (2-way agree): %d  (game %d, plugin %d)"
          % (len(parsed), len(game), len(plug)))
    for g in sorted(by_group):
        print("      group 0x%s : %d" % (g, len(by_group[g])))
    expect("ui files on disk", "ui_files", len(all_files))
    expect("layout scripts", "layout_scripts", len(parsed))
    expect("non-layout files", "non_layout_files", acc_info["n_nonlayout"])
    checks += 3

    # structural integrity of the depth tracking itself: every layout script's
    # <CHILDREN> nesting must balance, or the root enumeration is meaningless.
    unbalanced = [p for p in parsed if not p["balanced"]]
    print("  scripts with unbalanced <CHILDREN> : %d" % len(unbalanced))
    for p in unbalanced[:10]:
        print("      %s  final_depth=%d min_depth=%d"
              % (p["base"], p["final_depth"], p["min_depth"]))
    if unbalanced:
        fails.append(("unbalanced <CHILDREN> nesting", 0, len(unbalanced)))
    checks += 1

    # ---------- section 1b: POSITIVE CONTROL for the root enumerator ----------
    print()
    print("== SECTION 1b: POSITIVE CONTROL (can the parser see root #2 at all?) ==")
    pc_name, pc_roots = POSITIVE_CONTROL
    pc = [p for p in parsed if p["base"] == pc_name]
    if not pc:
        # A missing control is NOT a pass and NOT a skip - without it, every
        # "only one root here" below is an unproven null.
        print("  [FAIL] positive-control file absent : %s" % pc_name)
        print("         Every single-root result below is an UNPROVEN NULL.")
        fails.append(("positive control file present", 1, 0))
    else:
        got = len(pc[0]["roots"])
        ok = (got == pc_roots)
        print("  [%s] %s -> %d depth-0 roots (expected %d)"
              % ("OK " if ok else "FAIL", pc_name, got, pc_roots))
        print("         The pre-#99 parser scored this file 1. If this line ever")
        print("         reads 1 again, the first-<LEGACY>-only bug is back.")
        if not ok:
            fails.append(("positive control root count", pc_roots, got))
    checks += 1

    # ---------- section 2: roots + ids ----------
    all_roots = []          # flat list of (script, root)
    for p in parsed:
        for r in p["roots"]:
            all_roots.append((p, r))
    roots_with_id = [(p, r) for (p, r) in all_roots if r["id"]]
    rootless = [(p, r) for (p, r) in all_roots if not r["id"]]
    distinct_root_ids = set(r["id"] for (p, r) in all_roots)          # includes 0 bucket
    distinct_nonzero = set(r["id"] for (p, r) in roots_with_id)
    all_ids = set()
    for p in parsed:
        all_ids |= p["ids"]

    multi = [p for p in parsed if len(p["roots"]) > 1]
    zero_root_scripts = [p for p in parsed if len(p["roots"]) == 0]
    extra_roots = sum(len(p["roots"]) - 1 for p in parsed if len(p["roots"]) >= 1)

    print()
    print("== SECTION 2: roots and ids (depth-0 enumeration, ALL roots) ==")
    print("  depth-0 <LEGACY> roots      : %d" % len(all_roots))
    print("  roots with a nonzero id=    : %d" % len(roots_with_id))
    print("  roots with NO id            : %d" % len(rootless))
    print("  DISTINCT root ids           : %d  (%d nonzero + %d id-less bucket)"
          % (len(distinct_root_ids), len(distinct_nonzero),
             1 if rootless else 0))
    print("  DISTINCT ids anywhere       : %d" % len(all_ids))
    print("  multi-root scripts          : %d  (%d extra roots beyond one-per-script)"
          % (len(multi), extra_roots))
    print("  scripts with ZERO roots     : %d" % len(zero_root_scripts))
    expect("depth-0 roots", "depth0_roots", len(all_roots))
    expect("roots with nonzero id", "roots_with_nonzero_id", len(roots_with_id))
    expect("distinct root ids", "distinct_root_ids", len(distinct_root_ids))
    expect("distinct nonzero root ids", "distinct_nonzero_root_ids", len(distinct_nonzero))
    expect("multi-root scripts", "multi_root_scripts", len(multi))
    expect("extra roots", "extra_roots", extra_roots)
    checks += 6

    if (len(multi), extra_roots) != (DOC_MULTI_ROOT_SCRIPTS, DOC_EXTRA_ROOTS):
        print()
        print("  ** DISCREPANCY vs coverage-matrix.md section 2 (reported, not forced) **")
        print("     doc says  : %d multi-root scripts / %d extra roots"
              % (DOC_MULTI_ROOT_SCRIPTS, DOC_EXTRA_ROOTS))
        print("     measured  : %d multi-root scripts / %d extra roots"
              % (len(multi), extra_roots))
        print("     arithmetic: %d roots - %d layout scripts = %d extra. The doc's %d"
              % (len(all_roots), len(parsed), len(all_roots) - len(parsed), DOC_EXTRA_ROOTS))
        print("                 is only reachable if a layout script declares ZERO")
        print("                 top-level roots; measured zero-root scripts = %d."
              % len(zero_root_scripts))
        print("     NOTE: the doc's headline ladder 339/282/330/329/117 no longer")
        print("     reproduces either, and NOT because the doc mis-copied a number.")
        print("     The doc's recount used the same exact-banner filter this tool")
        print("     did, so it inherited the SAME blind spot: 1 UTF-8-BOM'd game")
        print("     script + 7 '# Generated by UIEditor' plugin scripts. Corrected:")
        print("       layout scripts  282 -> %d" % len(parsed))
        print("       depth-0 roots   330 -> %d" % len(all_roots))
        print("       with nonzero id 329 -> %d" % len(roots_with_id))
        print("       distinct ids    117 -> %d  (116 -> %d nonzero)"
              % (len(distinct_root_ids), len(distinct_nonzero)))
        print("     Doc owner should reconcile coverage-matrix.md section 2.")

    print("  --- multi-root scripts ---")
    for p in sorted(multi, key=lambda q: (-len(q["roots"]), q["base"])):
        print("      %d roots  %-40s %s"
              % (len(p["roots"]), p["base"],
                 " ".join("0x%08X" % r["id"] for r in p["roots"])))

    # duplicate root ids = candidate stale copies. TWO different questions,
    # kept apart on purpose because they answer to different claims:
    #   (a) how many root ids are declared by more than one ROOT RECORD
    #       (includes the same instance packed under two group ids);
    #   (b) how many are declared by more than one DISTINCT SCRIPT INSTANCE
    #       - this is coverage-matrix.md section 3.5's "stale copy" question.
    dupes = {}
    for (p, r) in roots_with_id:
        dupes.setdefault(r["id"], []).append((p, r))
    dupes = {k: v for k, v in dupes.items() if len(v) > 1}
    by_instance = {}
    for (p, r) in roots_with_id:
        by_instance.setdefault(r["id"], set()).add(p["inst"])
    stale = {k: v for k, v in by_instance.items() if len(v) > 1}
    print()
    print("  root ids at >1 ROOT RECORD  : %d" % len(dupes))
    print("  root ids in >1 SCRIPT INSTANCE (section 3.5 'stale copies') : %d"
          % len(stale))
    expect("stale-copy root ids", "stale_copy_root_ids", len(stale))
    for rid in sorted(dupes):
        cps = dupes[rid]
        print("      0x%08X : %s" % (rid, ", ".join(
            "I-%s(%d nodes,g%s)" % (p["inst"], r["nodes"], p["group"]) for (p, r) in cps)))
    checks += 2

    # ---------- section 3: UiSpike lists ----------
    print()
    print("== SECTION 3: src\\UiSpike.cpp id lists ==")
    lists = {}
    if not os.path.isfile(UISPIKE):
        print("  [SKIP] %s not found" % UISPIKE)
        skips.append(("UiSpike.cpp id lists", "file not found: %s" % UISPIKE,
                      "restore src\\UiSpike.cpp, then re-run"))
        skips.append(("SECTION 5 coverage ratio", "depends on UiSpike.cpp",
                      "restore src\\UiSpike.cpp, then re-run"))
        cpp = ""
    else:
        with open(UISPIKE, "r", encoding="latin-1") as f:
            cpp = f.read()
        for name in ("kNeverScaleIds", "kDataScaledSubtreeIds", "kAlwaysScaleCityIds",
                     "kCityDialogIds", "SCALED_WINDOW_IDS", "kSkipScaleIds"):
            ids, line = cpp_id_list(cpp, name)
            if ids is None:
                print("  %-24s : (not found as an array)" % name)
                skips.append(("UiSpike list %s" % name,
                              "no `const uint32_t %s[]` array in UiSpike.cpp" % name,
                              "confirm the list was renamed/removed, then update this "
                              "tool's list of array names"))
                continue
            lists[name] = ids
            print("  %-24s : %3d ids   (UiSpike.cpp:%d)" % (name, len(set(ids)), line))
    checks += 1

    # every id mentioned anywhere in UiSpike.cpp as a 0x........ literal
    cpp_ids = set(int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{8})\b", cpp))

    # ---------- section 4: art packages ----------
    print()
    print("== SECTION 4: art package manifests ==")
    for name in ("package-list.txt", "package-list-15x.txt", "package-list-3x.txt"):
        p = os.path.join(REPO, "tools", "selective-safe", name)
        n = 0
        if os.path.isfile(p):
            with open(p, "r", encoding="latin-1") as f:
                for ln in f:
                    n += 1
        else:
            skips.append(("art manifest %s" % name, "file not found",
                          "regenerate tools\\selective-safe\\%s" % name))
        print("  selective-safe\\%-20s : %d lines" % (name, n))
    refmap = os.path.join(REPO, "tools", "selective-safe", "refmap.csv")
    if os.path.isfile(refmap):
        with open(refmap, "r", encoding="latin-1") as f:
            rows = f.read().splitlines()
        print("  selective-safe\\refmap.csv        : %d rows" % (len(rows) - 1))
    else:
        print("  selective-safe\\refmap.csv        : (missing)")
        skips.append(("refmap.csv row count", "file not found",
                      "regenerate tools\\selective-safe\\refmap.csv"))
    checks += 1

    # ---------- section 5: coverage recompute ----------
    print()
    print("== SECTION 5: coverage recompute (RUNTIME LIST ONLY) ==")
    print("  SCOPE - read this before quoting any number below:")
    print("    * denominator = ALL %d depth-0 roots with a nonzero id." % len(roots_with_id))
    print("      This denominator has been WRONG TWICE. History, so nobody")
    print("      re-quotes a superseded ratio:")
    print("        281  one-root-per-script      ratio 241/281 = 85.8%  <- quoted as proof")
    print("        329  roots fixed, corpus not  ratio 286/329 = 86.9%")
    print("        %3d  corpus fixed too         ratio computed below   <- current"
          % len(roots_with_id))
    print("    * 'covered' here means ONLY: the id appears as a 0x........ literal")
    print("      somewhere in src\\UiSpike.cpp. It does NOT include the")
    print("      dialog-static staged path, and it does NOT exclude dev-editor or")
    print("      third-party plugin roots.")
    print("    * THEREFORE this ratio is NOT comparable to coverage-matrix.md's")
    print("      96.6% (288/298), which uses a different numerator AND a")
    print("      different denominator. Quoting one as a check on the other is")
    print("      the exact error #99 was filed for.")
    print()

    if not cpp:
        print("  [SKIP] no UiSpike.cpp text - coverage ratio NOT computed.")
        print("         A skipped check is NOT a pass.")
        covered_by_id, uncovered, touched_any, untouched_any = [], [], [], []
    else:
        covered_by_id, uncovered = [], []
        for (p, r) in roots_with_id:
            (covered_by_id if r["id"] in cpp_ids else uncovered).append((p, r))
        print("  roots whose ROOT id is named in UiSpike.cpp : %d" % len(covered_by_id))
        print("  roots whose ROOT id is NOT named            : %d" % len(uncovered))
        print("  ratio                                       : %d/%d = %.1f%%"
              % (len(covered_by_id), len(roots_with_id),
                 100.0 * len(covered_by_id) / max(1, len(roots_with_id))))
        checks += 1

        # child-level: does ANY id in this ROOT'S OWN SUBTREE appear in UiSpike.cpp?
        touched_any, untouched_any = [], []
        for (p, r) in roots_with_id:
            (touched_any if (r["ids"] & cpp_ids) else untouched_any).append((p, r))
        print("  roots with ANY subtree id named in UiSpike : %d" % len(touched_any))
        print("  roots with NO id at all named              : %d" % len(untouched_any))
        print("  ratio                                       : %d/%d = %.1f%%"
              % (len(touched_any), len(roots_with_id),
                 100.0 * len(touched_any) / max(1, len(roots_with_id))))
        checks += 1

        # distinct-id view (the doc counts distinct ids, not root instances)
        cov_distinct = set(r["id"] for (p, r) in covered_by_id)
        print("  DISTINCT root ids named in UiSpike.cpp      : %d/%d = %.1f%%"
              % (len(cov_distinct), len(distinct_nonzero),
                 100.0 * len(cov_distinct) / max(1, len(distinct_nonzero))))
        checks += 1

        # ---- COVERAGE FLOORS: make a REGRESSION fail, not merely print small ----
        print()
        print("  --- coverage floors (a regression FAILS the run) ---")
        for key, measured, label in (
                ("roots_root_id_named",     len(covered_by_id), "roots w/ root id named"),
                ("roots_any_id_named",      len(touched_any),   "roots w/ any id named"),
                ("distinct_root_ids_named", len(cov_distinct),  "distinct root ids named")):
            floor = COVERAGE_FLOOR[key]
            if measured < floor:
                print("  [FAIL] %-26s floor %-4d measured %d  <-- COVERAGE REGRESSED"
                      % (label, floor, measured))
                fails.append(("coverage floor: " + label, floor, measured))
            elif measured > floor:
                print("  [OK ] %-26s floor %-4d measured %d  (IMPROVED - raise the"
                      " floor to %d)" % (label, floor, measured, measured))
            else:
                print("  [OK ] %-26s floor %-4d measured %d" % (label, floor, measured))
            checks += 1

        # ---- THE CANONICAL FIGURE ----------------------------------------
        # User decision 2026-08-03: the STRICTEST view is canonical. Four views
        # existed and were quoted interchangeably, which is precisely how #99
        # hid for weeks - a denominator nobody checked, used as an independent
        # check on itself. Distinct-id is strictest because many roots SHARE an
        # id: covering one instance of an id does not cover the id. It is the
        # number that cannot flatter us, which is why it was chosen.
        print()
        print("  " + "=" * 66)
        print("  CANONICAL COVERAGE: %d/%d DISTINCT root ids named = %.1f%%"
              % (len(cov_distinct), len(distinct_nonzero),
                 100.0 * len(cov_distinct) / max(1, len(distinct_nonzero))))
        print("  " + "=" * 66)
        print("  This is THE figure. Quote no other without naming its scope.")
        print("  NOT comparable to coverage-matrix.md's 96.6% (288/298, D1) or")
        print("  94.9% (299/315, D1+D2) - those count script-declared shipping")
        print("  roots, a different denominator. Never do arithmetic across them.")

        print()
        print("  --- roots with NO id named anywhere in UiSpike.cpp ---")
        for (p, r) in sorted(untouched_any, key=lambda q: q[1]["id"]):
            a = r["area"] or (0, 0, 0, 0)
            print("      0x%08X  %-38s %4dx%-4d  %3d nodes  g%s"
                  % (r["id"], "I-" + p["inst"], a[2] - a[0], a[3] - a[1],
                     r["nodes"], p["group"]))

    # ---------- verdict ----------
    print()
    print("CHECKS RUN     : %d" % checks)
    print("SKIPPED        : %d   (a SKIPPED check is NEVER a pass)" % len(skips))
    for (label, reason, clear) in skips:
        print("   SKIP %-28s reason: %s" % (label, reason))
        print("        cleared by: %s" % clear)
    print("FAILED         : %d" % len(fails))
    for (label, want, got) in fails:
        print("   FAIL %-28s expected %s, measured %s" % (label, want, got))

    if fails:
        print()
        print("!" * 74)
        print("!! OVERALL: FAIL - %d hard expectation(s) diverged." % len(fails))
        print("!! DO NOT quote any number from this run. Either the corpus changed")
        print("!! (update EXPECT and say so in coverage-matrix.md) or the parser")
        print("!! regressed. Task #99 exists because this script once printed a")
        print("!! plausible WRONG number and exited 0.")
        print("!" * 74)
    else:
        print("OVERALL: PASS  (%d checks held, %d skipped)" % (checks, len(skips)))

    if out_json:
        with open(out_json, "w", encoding="utf-8", newline="\n") as f:
            json.dump(dict(
                n_files=len(all_files), n_layout=len(parsed),
                n_roots=len(all_roots), n_roots_with_id=len(roots_with_id),
                n_rootless=len(rootless),
                n_distinct_root_ids=len(distinct_root_ids),
                n_distinct_nonzero_root_ids=len(distinct_nonzero),
                n_multi_root_scripts=len(multi), n_extra_roots=extra_roots,
                multi_root_scripts={p["base"]: ["0x%08X" % r["id"] for r in p["roots"]]
                                    for p in multi},
                n_distinct_ids=len(all_ids),
                dup_root_ids={"0x%08X" % k: [p["inst"] for (p, r) in v]
                              for k, v in dupes.items()},
                n_stale_copy_root_ids=len(stale),
                stale_copy_root_ids={"0x%08X" % k: sorted(v) for k, v in stale.items()},
                lists={k: len(set(v)) for k, v in lists.items()},
                untouched=[dict(root="0x%08X" % r["id"], inst=p["inst"],
                                area=r["area"], nodes=r["nodes"],
                                group=p["group"]) for (p, r) in untouched_any],
                uncovered_root_id_only=[dict(root="0x%08X" % r["id"], inst=p["inst"])
                                        for (p, r) in uncovered],
                accounting=acc_info,
                expectations=EXPECT,
                expectations_before_corpus_fix=EXPECT_BEFORE_CORPUS_FIX,
                coverage_floor=COVERAGE_FLOOR,
                failures=[dict(label=l, expected=w, measured=g) for (l, w, g) in fails],
                skips=[dict(label=l, reason=r, cleared_by=c) for (l, r, c) in skips],
            ), f, indent=2)
        print("wrote %s" % out_json)
    return 0 if not fails else 1


def _run_injection(name, patcher, describe):
    """Run main() with a deliberate defect injected; the net must REJECT it."""
    print()
    print("#" * 74)
    print("# SELFTEST CASE: %s" % name)
    for ln in describe:
        print("#   %s" % ln)
    print("# EXPECTED RESULT: this run must FAIL (rc != 0).")
    print("#" * 74)
    print()
    undo = patcher()
    try:
        rc = main()
    finally:
        undo()
    print()
    if rc == 0:
        print("# >>> SELFTEST CASE FAILED: broken instrument ACCEPTED (rc=0). <<<")
        return 1
    print("# >>> SELFTEST CASE PASSED: rejected with rc=%d. <<<" % rc)
    return 0


def selftest():
    """NEGATIVE CONTROL for the regression net itself.

    Re-injects BOTH known #99 defects, one at a time, and demands that main()
    FAILS on each. A regression net that has never been seen to fail is not
    evidence that it works - and the corpus-filter defect (case 2) is one that
    the net as shipped on 2026-08-03 morning did NOT catch, because EXPECT had
    been frozen to the post-drop numbers.
    """
    results = []

    # ---- case 1: the original 'break at first <LEGACY>' ----
    def patch_first_root_only():
        g = globals()
        orig = g["parse_script"]

        def broken(path):
            p = orig(path)
            if p:
                p["roots"] = p["roots"][:1]     # <-- the old `break`
            return p
        g["parse_script"] = broken
        return lambda: g.__setitem__("parse_script", orig)

    results.append(_run_injection(
        "1/4 - numerator: keep only the FIRST depth-0 root per file",
        patch_first_root_only,
        ["This is the defect named in coverage-matrix.md section 3.",
         "It silently collapsed 21 multi-root scripts to one root each."]))

    # ---- case 2: the corpus filter that was documented-as-fixed but was not ----
    def patch_exact_banner_filter():
        g = globals()
        orig_banner = g["banner_ok"]
        orig_content = g["content_ok"]

        # Restore the exact-string, BOM-blind, case-sensitive test AND make the
        # content classifier agree with it, i.e. reproduce a SILENT drop rather
        # than a classifier disagreement. This is the harder case: it is what
        # the tool actually did, and it must still be caught.
        def broken_banner(text):
            return text.lstrip().startswith(BANNER)
        g["banner_ok"] = broken_banner
        g["content_ok"] = broken_banner
        return lambda: (g.__setitem__("banner_ok", orig_banner),
                        g.__setitem__("content_ok", orig_content))

    results.append(_run_injection(
        "2/4 - denominator: exact-string BOM-blind banner filter (silent drop)",
        patch_exact_banner_filter,
        ["Drops 1 UTF-8-BOM'd game script and 7 '# Generated by UIEditor'",
         "plugin scripts = 8 depth-0 roots. Both classifiers are broken the",
         "SAME way on purpose, so accounting() sees no disagreement and only",
         "the EXPECT totals can catch it. If this case passes, EXPECT has",
         "been re-frozen to a post-drop corpus again."]))

    # ---- case 3: a defect INSIDE the shared enumerator ----
    # The pre-fix accounting() could not see this: it re-called the same pure
    # function and compared it with itself. Measured before the fix, with 48 of
    # 338 roots gone, it still printed "290 carried / 290 fresh ... [OK ]".
    def patch_enumerator_first_root_only():
        g = globals()
        orig = g["enumerate_roots"]

        def broken(text):
            roots, d, md = orig(text)
            return roots[:1], d, md
        g["enumerate_roots"] = broken
        return lambda: g.__setitem__("enumerate_roots", orig)

    results.append(_run_injection(
        "3/4 - ROOT CONSERVATION must catch a drop INSIDE enumerate_roots",
        patch_enumerator_first_root_only,
        ["Same drop as case 1, but injected one level lower - in the enumerator",
         "the census and CLASSIFIER B share. Only a parser that shares no code",
         "with it (enumerate_roots_streamwise) can contradict it. Look for",
         "'[FAIL] ROOT CONSERVATION' in the run below; if that line is missing",
         "the reconciliation has gone back to comparing a function to itself."]))

    # ---- case 4: the corpus enumeration silently losing a directory ----
    # script_files() returns [] for a directory that does not exist. all_files
    # and records both shrink together, so no partition arithmetic can see it.
    def patch_drop_plugin_dir():
        g = globals()
        orig = g["script_files"]

        def broken(d):
            if d == SCRIPTS_PLUGINS:
                return []          # <-- the `if not os.path.isdir(d)` path
            return orig(d)
        g["script_files"] = broken
        return lambda: g.__setitem__("script_files", orig)

    results.append(_run_injection(
        "4/4 - FILE CONSERVATION must catch a silently vanished source dir",
        patch_drop_plugin_dir,
        ["script_files() returns [] for a missing directory, so the census and",
         "its own verdict partition agree on a truncated corpus. Only an",
         "enumeration that does not derive from script_files() - the recursive",
         "walk - can contradict it. Look for '[FAIL] FILE CONSERVATION'."]))

    print()
    print("#" * 74)
    if any(results):
        print("# SELFTEST FAILED: %d of %d injected defects were ACCEPTED."
              % (sum(results), len(results)))
        print("# The net does NOT catch #99. Fix EXPECT / accounting / controls.")
        print("#" * 74)
        return 1
    print("# SELFTEST PASSED: all %d injected defects were rejected." % len(results))
    print("# (Ignore the FAIL banners above - they are the point of this mode.)")
    print("#" * 74)
    return 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    sys.exit(main())
