r"""Emit the list of art TGIs that are PROVABLY 9-slice frames and NEVER state
strips (#157).

⛔ WHY THIS EXISTS. `CellUnit` takes the LCM of every count in {3,4} that
divides the sheet, on the reasoning that preserving divisibility is free. It is
not free, because the two counts want DIFFERENT sizes and only one of them is
real for any given sheet:

    180x180 dialog frame, factor 1.5
      /3 wants  3 * round(60 * 1.5) = 270      <- the NineSlice cell
      /4 wants  4 * round(45 * 1.5) = 272      <- a cut this sheet does not have
      LCM 12 snap                   = 276      <- what shipped

The sheet is a 9-slice frame. Nothing ever cuts it into four states; 180 merely
happens to divide by 4. Sizing it 276 makes the engine's `img->Width()/3` cell
92 where every geometry number in the `.UI` was scaled for 90, so the corner art
is drawn 2px oversized and the rounded corner stops short of the window corner —
a navy block juts past the arc with a transparent notch at the corner. MEASURED
on the Reconcile Edges dialog (#157): 418 uncovered pixels at 1.5x, 4 with a
270 sheet, 0 at 2x and 3x.

THE UNDERLYING LAW IS #156's, ONE SHEET FURTHER ON: a heuristic that IDENTIFIES
a structure is safe for PROTECTING it and unsafe for RESIZING it. "180 divides
by 4" is not evidence of four states. The `.UI` that BINDS the sheet is.

    9-slice   `blttype=edge` on the node, or `edgeimage=yes` on a GZWinBMP
    strip     the node is a GZWinBtn drawing one state of the sheet

A TGI qualifies here only if some script draws it as a 9-slice and NO script
ever draws it as a button, and it is absent from `cell-strips.txt` (the #156
derivation, which uses independent evidence — window size — so agreement
between the two is not two instruments agreeing blindly, and disagreement is a
reason to exclude, never to include).

⚠ THE .UI CORPUS IS NOT THE WHOLE TRUTH. Art binds by TGI and some consumers
are created at runtime and appear in no script (REGRESSION.md #148). That is
why this list is EXCLUSION-BIASED: a sheet nobody proved is a 9-slice keeps the
sizing it has today, so an unknown runtime strip consumer can only be missed by
this list, never broken by it.

    python find_nine_slice.py [--out nine-slice.txt]

Read-only apart from its own output file.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
UI_DIRS = [os.path.join(TOOLS, "uiscripts", "extracted"),
           os.path.join(TOOLS, "dialog-static", "thirdparty-src")]
STRIPS = os.path.join(HERE, "cell-strips.txt")

ATTR = re.compile(r'(\w+)=("[^"]*"|\{[^}]*\}|\([^)]*\)|\S+)')
IMG = re.compile(r"\{([0-9a-fA-F]+),([0-9a-fA-F]+)\}")


def scan():
    """(gid,iid) -> set of the roles the scripts give that sheet."""
    use = {}
    files = 0
    for d in UI_DIRS:
        if not os.path.isdir(d):
            continue
        for fn in os.listdir(d):
            if not fn.endswith(".ui"):
                continue
            files += 1
            with open(os.path.join(d, fn), "r", encoding="latin-1") as fh:
                txt = fh.read()
            for m in re.finditer(r"<LEGACY([^>]*)>", txt):
                a = dict(ATTR.findall(m.group(1)))
                gi = IMG.match(a.get("image", ""))
                if not gi:
                    continue
                k = (gi.group(1).lower(), gi.group(2).lower())
                if a.get("blttype") == "edge" or a.get("edgeimage") == "yes":
                    role = "edge"
                elif a.get("clsid") == "GZWinBtn":
                    role = "btn"
                else:
                    role = "plain"
                use.setdefault(k, set()).add(role)
    return use, files


def proven_strips():
    out = set()
    if not os.path.isfile(STRIPS):
        return out
    with open(STRIPS, "r", encoding="utf-8") as fh:
        for line in fh:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            p = s.split()
            if len(p) >= 2:
                out.add((p[0].lower(), p[1].lower()))
    return out


def main():
    out = "nine-slice.txt"
    if "--out" in sys.argv:
        out = sys.argv[sys.argv.index("--out") + 1]
    use, files = scan()
    strips = proven_strips()

    picked, rejected = [], []
    for k in sorted(use):
        roles = use[k]
        if "edge" not in roles:
            continue
        if "btn" in roles:
            rejected.append((k, "also drawn as a button strip"))
        elif k in strips:
            rejected.append((k, "listed in cell-strips.txt"))
        else:
            picked.append(k)

    lines = [
        "# Art TGIs PROVEN to be 9-slice frames and never state strips (#157).",
        "# Generated by tools\\upscale\\find_nine_slice.py - do not hand-edit.",
        "# Derived, not guessed: a .UI draws the sheet with blttype=edge or",
        "# edgeimage=yes, and NO .UI ever draws it as a GZWinBtn state.",
        "# Upscale2x sizes these with CellUnit {3} only, so the NineSlice cell",
        "# img->Width()/3 stays proportional to the geometry at a fractional tier.",
        "# <group> <instance>",
    ]
    lines += ["%s %s" % k for k in picked]
    with open(os.path.join(HERE, out) if not os.path.isabs(out) else out,
              "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    print("scanned %d .UI files, %d art TGIs referenced" % (files, len(use)))
    print("9-slice, never a strip : %d  -> %s" % (len(picked), out))
    for k, why in rejected:
        print("  EXCLUDED %s,%s - %s" % (k[0], k[1], why))
    if not picked:
        # A silent empty list would read exactly like "nothing needs this",
        # which is the shape of every vacuous pass this project has shipped.
        print("REFUSING TO BE QUIET: zero sheets matched. The corpus is either "
              "missing or the role predicate is wrong - do NOT treat this as "
              "'no work to do'.")
        return 1
    return 0


sys.exit(main())
