r"""Emit the list of art TGIs that are PROVABLY tiled backgrounds, and so have
NO cell divide of any kind to preserve (#160).

⛔ WHY THIS EXISTS. This is #157's law one structure further on. `CellUnit`
snaps a scaled sheet to keep a cell count dividing evenly - correct for a
4-state strip (`width/4`) and for a 9-slice frame (`img->Width()/3`). A
`blttype=tiled` background HAS NEITHER. It is drawn src-follows-dst: the engine
repeats the source across the destination, so the ONLY thing that matters is
that the scaled sheet still matches the scaled WINDOW. Snapping it does the one
thing that cannot help and can hurt - it desynchronises the two:

    god toolbar rail {46a006b0,14415876}, 1x art 74x351 == its window 74x351
      1x    art 74x351   window 74x351    delta 0
      2x    art 148x702  window 148x702   delta 0
      1.5x  art 111x528  window 111x527   delta +1   <- ScaleDim snapped 527->528
                                                        (CellUnit(351)=3)

USER-REPORTED as "a break in the white line on the left that is not in 2x or
stock" - the god-mode tool column, at 1.5x only. An integer factor cannot
produce it: there the snap is a provable no-op, which is exactly why 2x and
stock are clean and only the fractional tier shows it.

A TGI qualifies here only if some script draws it with `blttype=tiled`, NO
script draws it as a `GZWinBtn` state or as a 9-slice (`blttype=edge` /
`edgeimage=yes`), and it is absent from BOTH `cell-strips.txt` (#156) and
`nine-slice.txt` (#157). Those two lists are derived from independent evidence -
window size and blit type - so agreeing with them is corroboration, and
disagreeing is a reason to exclude, never to include.

⚠ EXCLUSION-BIASED ON PURPOSE, like its two siblings. Art binds by TGI and some
consumers are created at runtime and appear in no script (REGRESSION.md #148),
so a sheet nobody proved is a tiled background keeps the sizing it has today.
An unknown consumer can be MISSED by this list, never broken by it.

    python find_tiled.py [--out tiled.txt]

Read-only apart from its own output file.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
UI_DIRS = [os.path.join(TOOLS, "uiscripts", "extracted"),
           os.path.join(TOOLS, "dialog-static", "thirdparty-src")]
SIBLINGS = [os.path.join(HERE, "cell-strips.txt"),
            os.path.join(HERE, "nine-slice.txt")]

ATTR = re.compile(r'(\w+)=("[^"]*"|\{[^}]*\}|\([^)]*\)|\S+)')
IMG = re.compile(r"\{([0-9a-fA-F]+),([0-9a-fA-F]+)\}")


def scan():
    use, files = {}, 0
    for d in UI_DIRS:
        if not os.path.isdir(d):
            continue
        for fn in os.listdir(d):
            if not fn.endswith(".ui"):
                continue
            files += 1
            with open(os.path.join(d, fn), "r", encoding="latin-1") as fh:
                txt = fh.read()
            for m in re.finditer(r"<LEGACY([^>]*)>", txt):
                a = dict(ATTR.findall(m.group(1)))
                gi = IMG.match(a.get("image", ""))
                if not gi:
                    continue
                k = (gi.group(1).lower(), gi.group(2).lower())
                if a.get("blttype") == "tiled":
                    role = "tiled"
                elif a.get("blttype") == "edge" or a.get("edgeimage") == "yes":
                    role = "edge"
                elif a.get("clsid") == "GZWinBtn":
                    role = "btn"
                else:
                    role = "plain"
                use.setdefault(k, set()).add(role)
    return use, files


def listed():
    out = set()
    for p in SIBLINGS:
        if not os.path.isfile(p):
            continue
        with open(p, "r", encoding="utf-8") as fh:
            for line in fh:
                s = line.strip()
                if not s or s.startswith("#"):
                    continue
                q = s.split()
                if len(q) >= 2:
                    out.add((q[0].lower(), q[1].lower()))
    return out


def main():
    out = "tiled.txt"
    if "--out" in sys.argv:
        out = sys.argv[sys.argv.index("--out") + 1]
    use, files = scan()
    other = listed()

    picked, rejected = [], []
    for k in sorted(use):
        roles = use[k]
        if "tiled" not in roles:
            continue
        clash = roles & {"btn", "edge"}
        if clash:
            rejected.append((k, "also drawn as " + "/".join(sorted(clash))))
        elif k in other:
            rejected.append((k, "listed in cell-strips.txt or nine-slice.txt"))
        else:
            picked.append(k)

    lines = [
        "# Art TGIs PROVEN to be tiled backgrounds with NO cell divide (#160).",
        "# Generated by tools\\upscale\\find_tiled.py - do not hand-edit.",
        "# Derived, not guessed: a .UI draws the sheet with blttype=tiled, and no",
        "# .UI ever draws it as a GZWinBtn state or as a 9-slice.",
        "# Upscale2x sizes these with NO snap at all, so the scaled sheet still",
        "# matches its scaled WINDOW - the only thing a tiled blit cares about.",
        "# <group> <instance>",
    ]
    lines += ["%s %s" % k for k in picked]
    path = out if os.path.isabs(out) else os.path.join(HERE, out)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    print("scanned %d .UI files, %d art TGIs referenced" % (files, len(use)))
    print("tiled, no cell divide : %d  -> %s" % (len(picked), out))
    for k, why in rejected:
        print("  EXCLUDED %s,%s - %s" % (k[0], k[1], why))
    if not picked:
        print("REFUSING TO BE QUIET: zero sheets matched. Either the corpus is "
              "missing or the predicate is wrong - do NOT read this as "
              "'nothing needs it'.")
        return 1
    return 0


sys.exit(main())
