r"""DERIVE thumbnails.txt - the art the engine binds as ITEM ICONS (lot / building
thumbnails), which keeps the plain copy path at a fractional factor.

WHY (2026-09-01, in-game A/B round 1). Under the straight-edge hybrid the user
judged the UI chrome "a lot better" and the thumbnails "still not as sharp".
No source-structure predicate separates the two: the glossy mode buttons the
hybrid improved read ramp_frac 0.74-0.99 and stroke density 0.05-0.08, the
thumbnails 0.47-0.86 and 0.08 (tools\research\sharp15\ramp_census.py,
stroke_census.py). What differs is what the picture DEPICTS - a rendered
building wants hard pixels (the 2x/3x block copy is the reference), a button
wants its outline consistent and its corners smooth. That is a binding fact,
not a pixel fact, so the class is derived from the binding: every TGI the
item-icon packages carry. Those packages are built from the game's own
item-icon references (stage_icons.py's item_icons_distinct.txt is read off the
exemplars; build_itemicons_sub.py from the submenu/plugin icon sets), so this
list is the engine's "this is a menu thumbnail" set, at second hand.

Reads the DBPF index of the packaged dats directly (index 7.0: 20-byte
entries T,G,I,offset,size) - no dependency on the extraction toolchain.

    python find_thumbnails.py            # writes tools\upscale\thumbnails.txt

Offline. Reads tools\packages\15x\z_SC4UIScale_ItemIcons-15x.dat and
z_SC4UIScale_ItemIconsSub-15x.dat (any tier's copy carries the same TGIs).
"""
import os
import struct
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
PKG = os.path.join(TOOLS, "packages", "15x")
DATS = ["z_SC4UIScale_ItemIcons-15x.dat", "z_SC4UIScale_ItemIconsSub-15x.dat"]
PNG_TYPE = 0x856DDBAC
OUT = os.path.join(HERE, "thumbnails.txt")


def dbpf_tgis(path):
    with open(path, "rb") as fh:
        hdr = fh.read(96)
        if hdr[:4] != b"DBPF":
            raise SystemExit("not a DBPF: %s" % path)
        major, minor = struct.unpack_from("<II", hdr, 4)
        idx_major, = struct.unpack_from("<I", hdr, 0x20)
        count, offset, size = struct.unpack_from("<III", hdr, 0x24)
        fh.seek(offset)
        data = fh.read(size)
    entries = []
    stride = 20
    if idx_major == 7 and size >= count * stride:
        for k in range(count):
            t, g, i, off, sz = struct.unpack_from("<IIIII", data, k * stride)
            entries.append((t, g, i))
    else:
        raise SystemExit("unexpected index layout %d.x (count %d size %d) in %s" % (idx_major, count, size, path))
    return entries


def main():
    tgis = set()
    per = {}
    for d in DATS:
        p = os.path.join(PKG, d)
        if not os.path.exists(p):
            raise SystemExit("missing %s - build the 1.5x icon packages first" % p)
        e = [x for x in dbpf_tgis(p) if x[0] == PNG_TYPE]
        per[d] = len(e)
        tgis.update((g, i) for _, g, i in e)
    if len(tgis) < 300:
        raise SystemExit("only %d thumbnail TGIs - the packages should carry ~480; refusing to write" % len(tgis))
    groups = {}
    for g, i in tgis:
        groups[g] = groups.get(g, 0) + 1
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Art the engine binds as ITEM ICONS (lot / building thumbnails).\n")
        fh.write("# Generated by tools\\upscale\\find_thumbnails.py - do not hand-edit.\n")
        fh.write("# Derived, not guessed: every PNG the ItemIcons + ItemIconsSub packages\n")
        fh.write("# carry, i.e. what stage_icons.py reads off the exemplars' item-icon\n")
        fh.write("# references and what build_itemicons_sub.py packs from the submenu sets.\n")
        fh.write("# At a fractional factor these keep the plain copy path (nearest): a\n")
        fh.write("# rendered picture wants hard pixels, the user's 2026-09-01 verdict.\n")
        fh.write("# sources: %s\n" % ", ".join("%s=%d" % (k, v) for k, v in per.items()))
        fh.write("# groups: %s\n" % ", ".join("%08x=%d" % (g, n) for g, n in sorted(groups.items())))
        fh.write("# <group> <instance>\n")
        for g, i in sorted(tgis):
            fh.write("%08x %08x\n" % (g, i))
    print("wrote %s: %d TGIs from %s; groups %s" % (OUT, len(tgis), per, {("%08x" % g): n for g, n in groups.items()}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
