# Does the DLL find its own two folders, in every layout it can be installed in?
#
# WHY THIS EXISTS. v4.5.0 replaced hard-coded folder names with discovery BY
# CONTENT so the mod would survive a package manager naming the folders itself.
# Nothing tested it. The discovery capped its walk at two levels below the
# Plugins root, and the channel entry puts the EARLY package's marker files
# three levels down - so on an sc4pac install the early half was never found,
# fell back to a folder that does not exist, and every early package stayed
# pinned at whatever tier shipped in the zip while the override half armed
# correctly. A mixed-scale UI, from a layout no test had ever built.
#
# HOW IT WORKS. The discovery code is lifted VERBATIM out of src/ScaleTier.cpp
# between the FOLDER-DISCOVERY sentinels, compiled standalone with the single
# external call (PluginsRootQuiet) stubbed, and run against simulated trees
# built from the real shipped filenames. Extraction is by sentinel, not line
# number: the test cannot drift away from the code without failing to build.
#
#   .\_tests\Test-FolderDiscovery.ps1
[CmdletBinding()]
param(
    [string]$Bundle,
    [switch]$KeepTrees
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$src  = Join-Path $repo 'src\ScaleTier.cpp'
$work = Join-Path $env:TEMP 'sc4uiscale-discovery'

if (-not $Bundle) {
    $Bundle = Get-ChildItem (Join-Path $repo 'dist') -Directory -Filter 'SC4UIScale-v*' -EA SilentlyContinue |
              Where-Object { $_.Name -notlike '*-dev' } |
              Sort-Object Name -Descending | Select-Object -First 1 -ExpandProperty FullName
}
if (-not $Bundle -or -not (Test-Path (Join-Path $Bundle 'Plugins'))) {
    throw "no built bundle found; pass -Bundle <dist\SC4UIScale-vX.Y.Z>"
}
Write-Output "bundle: $Bundle"

# ---- LIFT THE CODE -----------------------------------------------------------
$lines = Get-Content $src
$b = ($lines | Select-String -SimpleMatch '==== BEGIN FOLDER-DISCOVERY' | Select-Object -First 1).LineNumber
$e = ($lines | Select-String -SimpleMatch '==== END FOLDER-DISCOVERY'   | Select-Object -First 1).LineNumber
if (-not $b -or -not $e -or $e -le $b) {
    throw "FOLDER-DISCOVERY sentinels not found in $src - the test cannot lift the code it is meant to cover"
}
$region = $lines[$b..($e - 2)] -join "`r`n"
Write-Output "lifted $($e - $b - 1) lines of discovery code from ScaleTier.cpp (lines $b..$e)"

# The lift must actually contain the functions, or a green run would be testing
# an empty file. This is the control for the extraction itself.
foreach ($fn in 'ClassifyDir', 'ScanForOurDirs', 'ResolveOurDirs') {
    if ($region -notmatch [regex]::Escape($fn)) { throw "lifted region does not contain $fn - extraction is wrong" }
}

if (Test-Path $work) { Remove-Item -LiteralPath $work -Recurse -Force }
New-Item -ItemType Directory $work -Force | Out-Null

$harness = @"
// GENERATED by _tests/Test-FolderDiscovery.ps1 - do not edit.
// The namespace body below is lifted verbatim from src/ScaleTier.cpp.
#include <windows.h>
#include <stdio.h>
#include <wchar.h>
namespace {
    wchar_t gRoot[MAX_PATH];
    bool PluginsRootQuiet(wchar_t* out, size_t outLen)
    { wcscpy_s(out, outLen, gRoot); return true; }
$region
}
int wmain(int argc, wchar_t** argv)
{
    if (argc < 2) { wprintf(L"usage: discover <plugins-root>\n"); return 2; }
    wcscpy_s(gRoot, MAX_PATH, argv[1]);
    if (gRoot[wcslen(gRoot) - 1] != L'\\') { wcscat_s(gRoot, MAX_PATH, L"\\"); }
    ResolveOurDirs();
    wprintf(L"earlyFound=%d earlyCandidates=%d early=%s\n",
        gOurDirs.earlyFound ? 1 : 0, gEarlyCandidates, gOurDirs.early);
    wprintf(L"ovrFound=%d ovrCandidates=%d override=%s\n",
        gOurDirs.overrideFound ? 1 : 0, gOvrCandidates, gOurDirs.override_);
    return 0;
}
"@
$hpath = Join-Path $work 'discover.cpp'
[IO.File]::WriteAllText($hpath, $harness, (New-Object Text.UTF8Encoding($false)))

# ---- COMPILE -----------------------------------------------------------------
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { throw 'vswhere.exe not found - Visual Studio is required to build the harness' }
$vs = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
$vcvars = Join-Path $vs 'VC\Auxiliary\Build\vcvars32.bat'
if (-not (Test-Path $vcvars)) { throw "vcvars32.bat not found under $vs" }

Push-Location $work
try {
    $bat = Join-Path $work 'build.bat'
    # CRLF: cmd.exe seeks by BYTE OFFSET on call/goto and lands mid-line in an
    # LF-only batch file. House law, paid for once already.
    $batText = "@echo off`r`ncall `"$vcvars`" >nul 2>&1`r`ncl /nologo /EHsc /W3 discover.cpp /Fe:discover.exe >build.log 2>&1`r`nexit /b %ERRORLEVEL%`r`n"
    [IO.File]::WriteAllText($bat, $batText, (New-Object Text.UTF8Encoding($false)))
    & cmd /c $bat
    if ($LASTEXITCODE -ne 0) {
        Write-Output 'HARNESS DID NOT COMPILE:'
        Get-Content (Join-Path $work 'build.log') | ForEach-Object { Write-Output "  $_" }
        throw 'the lifted discovery code does not compile standalone'
    }
} finally { Pop-Location }
Write-Output 'harness compiled'

# ---- BUILD THE SIMULATED TREES ----------------------------------------------
# Filenames come from the REAL bundle, so a rename in the payload breaks this
# test instead of sailing past it.
$earlyFiles = @(Get-ChildItem (Join-Path $Bundle 'Plugins\010-SC4UIScale') -File | ForEach-Object Name)
$ovrFiles   = @(Get-ChildItem (Join-Path $Bundle 'Plugins\zzz-SC4UIScale')  -File | ForEach-Object Name)
if ($earlyFiles.Count -lt 5 -or $ovrFiles.Count -lt 5) {
    throw "bundle looks wrong: $($earlyFiles.Count) early / $($ovrFiles.Count) override files"
}
Write-Output "tree contents: $($earlyFiles.Count) early file(s), $($ovrFiles.Count) override file(s)"

function New-Tree([string]$name, [string]$earlyRel, [string]$ovrRel, [string[]]$extraDirs) {
    $root = Join-Path $work "sim\$name\Plugins"
    New-Item -ItemType Directory $root -Force | Out-Null
    foreach ($d in $extraDirs) { New-Item -ItemType Directory (Join-Path $root $d) -Force | Out-Null }
    if ($earlyRel) {
        $d = Join-Path $root $earlyRel; New-Item -ItemType Directory $d -Force | Out-Null
        foreach ($f in $earlyFiles) { [IO.File]::WriteAllText((Join-Path $d $f), '') }
    }
    if ($ovrRel) {
        $d = Join-Path $root $ovrRel; New-Item -ItemType Directory $d -Force | Out-Null
        foreach ($f in $ovrFiles) { [IO.File]::WriteAllText((Join-Path $d $f), '') }
    }
    return $root
}

# The sc4pac shapes are not symmetric, and that asymmetry is the whole defect.
# sc4pac strips each package's longest common directory prefix:
#   early pkg also ships the DLL at /Plugins/, so the common prefix is only
#     /Plugins/ and 010-SC4UIScale/ SURVIVES -> markers three levels down
#   override pkg has every file under /Plugins/zzz-SC4UIScale/, so that whole
#     prefix is stripped -> markers two levels down
$PKG_E = 'a-drexel.sc4-ui-scale.4.5.0.sc4pac'
$PKG_O = 'a-drexel.sc4-ui-scale-mod-overrides.4.5.0.sc4pac'

$cases = @(
    @{ name = 'A_sc4pac';       early = "050-load-first\$PKG_E\010-SC4UIScale"; ovr = "900-overrides\$PKG_O"
       extra = @('050-load-first\cam.sc4-system-integration-module.4.0.1.sc4pac\1 CAM Core')
       expectEarly = 1; expectOvr = 1; expectEarlyCand = 1; expectOvrCand = 1
       why = 'the layout the shipped channel entry actually asks for' },
    @{ name = 'B_rootpkg';      early = "$PKG_E\010-SC4UIScale"; ovr = $PKG_O
       extra = @(); expectEarly = 1; expectOvr = 1; expectEarlyCand = 1; expectOvrCand = 1
       why = 'packages placed at the Plugins root, no category subfolder' },
    @{ name = 'C_handinstall';  early = '010-SC4UIScale'; ovr = 'zzz-SC4UIScale'
       extra = @(); expectEarly = 1; expectOvr = 1; expectEarlyCand = 1; expectOvrCand = 1
       why = 'CONTROL - the hand-installed layout that has always worked' },
    @{ name = 'D_splitbrain';   early = '010-SC4UIScale'; ovr = "900-overrides\$PKG_O"
       extra = @(); expectEarly = 1; expectOvr = 1; expectEarlyCand = 1; expectOvrCand = 1
       why = 'a hand install left behind while sc4pac manages the override half' }
)

# D also needs the sc4pac EARLY package present, so two directories carry the
# early marker and the ambiguity counter has something to report.
$fail = @()
Write-Output ''
foreach ($c in $cases) {
    $root = New-Tree $c.name $c.early $c.ovr $c.extra
    if ($c.name -eq 'D_splitbrain') {
        $d = Join-Path $root "050-load-first\$PKG_E\010-SC4UIScale"
        New-Item -ItemType Directory $d -Force | Out-Null
        foreach ($f in $earlyFiles) { [IO.File]::WriteAllText((Join-Path $d $f), '') }
        $c.expectEarlyCand = 2
    }
    $out = & (Join-Path $work 'discover.exe') $root
    $ef  = [int]([regex]::Match($out[0], 'earlyFound=(\d)').Groups[1].Value)
    $ec  = [int]([regex]::Match($out[0], 'earlyCandidates=(\d+)').Groups[1].Value)
    $of  = [int]([regex]::Match($out[1], 'ovrFound=(\d)').Groups[1].Value)
    $oc  = [int]([regex]::Match($out[1], 'ovrCandidates=(\d+)').Groups[1].Value)

    Write-Output "$($c.name)  - $($c.why)"
    Write-Output "  early    found=$ef candidates=$ec"
    Write-Output "  override found=$of candidates=$oc"

    if ($ef -ne $c.expectEarly) { $fail += "$($c.name): early half found=$ef, expected $($c.expectEarly) - every early package would fall back to a folder that may not exist and stay unarmed" }
    if ($of -ne $c.expectOvr)   { $fail += "$($c.name): override half found=$of, expected $($c.expectOvr)" }
    if ($ec -ne $c.expectEarlyCand) { $fail += "$($c.name): early candidates=$ec, expected $($c.expectEarlyCand)" }
    if ($oc -ne $c.expectOvrCand)   { $fail += "$($c.name): override candidates=$oc, expected $($c.expectOvrCand)" }
}

# ---- NEGATIVE CONTROL --------------------------------------------------------
# An empty tree MUST come back not-found. Without this, a discovery that
# returned "found" unconditionally would pass every case above.
$empty = Join-Path $work 'sim\E_empty\Plugins'
New-Item -ItemType Directory (Join-Path $empty '050-load-first\somebody-else.1.0.sc4pac') -Force | Out-Null
$out = & (Join-Path $work 'discover.exe') $empty
$ef = [int]([regex]::Match($out[0], 'earlyFound=(\d)').Groups[1].Value)
$of = [int]([regex]::Match($out[1], 'ovrFound=(\d)').Groups[1].Value)
Write-Output ''
Write-Output "E_empty (NEGATIVE CONTROL - a tree with none of our files)"
Write-Output "  early found=$ef  override found=$of   (both must be 0)"
if ($ef -ne 0 -or $of -ne 0) { $fail += 'NEGATIVE CONTROL FAILED: discovery reported our folders in a tree that has none of our files - every result above is meaningless' }

# ---- POSITIVE CONTROL FOR THE TEST ITSELF ------------------------------------
# A test that has never failed is a claim, not a measurement. Rebuild the same
# harness with the ONE character that caused the defect - the depth cap back at
# its old value - and require case A to fail. If this build still passes case A,
# the test is not sensitive to the thing it exists to catch and every ALL PASS
# above is worthless.
$mutant = $region -replace 'if \(depth > 3\) \{ return; \}', 'if (depth > 2) { return; }'
if ($mutant -eq $region) {
    $fail += 'MUTATION CONTROL COULD NOT BE BUILT: the depth cap line was not found in the lifted region, so this test cannot show it is sensitive to the defect'
} else {
    $mpath = Join-Path $work 'mutant.cpp'
    [IO.File]::WriteAllText($mpath, ($harness -replace [regex]::Escape($region), $mutant), (New-Object Text.UTF8Encoding($false)))
    Push-Location $work
    try {
        $mbat = Join-Path $work 'buildm.bat'
        [IO.File]::WriteAllText($mbat, "@echo off`r`ncall `"$vcvars`" >nul 2>&1`r`ncl /nologo /EHsc /W3 mutant.cpp /Fe:mutant.exe >buildm.log 2>&1`r`nexit /b %ERRORLEVEL%`r`n", (New-Object Text.UTF8Encoding($false)))
        & cmd /c $mbat
        if ($LASTEXITCODE -ne 0) { $fail += 'MUTATION CONTROL did not compile' }
    } finally { Pop-Location }

    if (Test-Path (Join-Path $work 'mutant.exe')) {
        $rootA = Join-Path $work 'sim\A_sc4pac\Plugins'
        $mout = & (Join-Path $work 'mutant.exe') $rootA
        $mef = [int]([regex]::Match($mout[0], 'earlyFound=(\d)').Groups[1].Value)
        Write-Output ''
        Write-Output 'MUTATION CONTROL (depth cap put back to 2, the shipped v4.5.0 value)'
        Write-Output "  A_sc4pac early found=$mef   (must be 0 - this is the defect)"
        if ($mef -ne 0) {
            $fail += 'MUTATION CONTROL FAILED: the old depth cap still resolves the early half on the sc4pac tree, so this test would not have caught the defect it was written for'
        }
    }
}

if (-not $KeepTrees) { Remove-Item -LiteralPath (Join-Path $work 'sim') -Recurse -Force -EA SilentlyContinue }

Write-Output ''
if ($fail.Count) {
    Write-Output 'RED:'
    $fail | ForEach-Object { Write-Output "  - $_" }
    exit 1
}
Write-Output 'ALL PASS - discovery resolves both folders in every install layout,'
Write-Output 'reports a second candidate, and finds nothing in a tree without us.'
exit 0
