#!/usr/bin/env python3
r"""#200 - DERIVE the set of sheets that actually NEED the even (area-average)
reduce at a fractional factor, so the average can be opt-in instead of the
default.

WHY: measured, the area-average softens 1714 of 2206 sheets (edge retention
0.7981 vs 0.9979 for the nearest sheets at the SAME factor) to buy a tick
EVENNESS property that only a small minority of sheets structurally exhibit.
The cure is to scope it - but scoping needs the real membership, DERIVED, not
a hand list and not an assumption that cell-strips.txt already covers it.

A sheet needs evenness when a row contains >=4 "ink" runs of IDENTICAL width
(1..8 px) against the row's dominant background - a regular tick/gauge ladder,
where nearest's parity makes some ticks 4px and others 5px at f=1.5.

Emits even-strips.txt in the same format as the other derived lists, and
reports the overlap with cell-strips.txt so the gap is visible rather than
assumed.
"""
import os
import re
import sys
from collections import Counter

import numpy as np
from PIL import Image

PROJ = r"C:\dev\SC4UIScale"
SRC = os.path.join(PROJ, "tools", "dbpf", "extracted", "SimCity_1")
OUT = os.path.join(PROJ, "tools", "upscale", "even-strips.txt")
CELL = os.path.join(PROJ, "tools", "upscale", "cell-strips.txt")
NAME = re.compile(r"T-(?:0x)?([0-9a-fA-F]{8})_G-(?:0x)?([0-9a-fA-F]{8})_I-(?:0x)?([0-9a-fA-F]{8})",
                  re.I)


def runs(vals, bg):
    out, c = [], 0
    for v in vals:
        if v != bg:
            c += 1
        elif c:
            out.append(c); c = 0
    if c:
        out.append(c)
    return out


def tickish(a):
    """True if any row is a regular tick ladder."""
    h, w = a.shape[:2]
    flat = a.reshape(h, w, -1)
    for y in range(h):
        row = [tuple(int(v) for v in p) for p in flat[y]]
        bg = Counter(row).most_common(1)[0][0]
        r = runs(row, bg)
        if len(r) >= 4 and 1 <= r[0] <= 8 and len(set(r)) == 1:
            return True
    return False


def main():
    if not os.path.isdir(SRC):
        print("SKIP: 1x extract absent (%s)" % SRC)
        return 0
    hits = []
    scanned = 0
    for n in sorted(os.listdir(SRC)):
        if not n.lower().endswith(".png"):
            continue
        m = NAME.search(n)
        if not m:
            continue
        p = os.path.join(SRC, n)
        try:
            a = np.asarray(Image.open(p).convert("RGBA"), dtype=np.uint8)
        except OSError:
            continue
        h, w = a.shape[:2]
        if w < 16 or w * h > 60000:
            continue
        scanned += 1
        if tickish(a):
            hits.append((m.group(2).lower(), m.group(3).lower()))
    if scanned == 0:
        print("FATAL: scanned zero sheets - the name filter is blind, this is a "
              "refusal not an empty result")
        return 1

    cell = set()
    if os.path.isfile(CELL):
        for ln in open(CELL, encoding="utf-8"):
            ln = ln.strip()
            if not ln or ln.startswith("#"):
                continue
            pp = ln.split()
            if len(pp) >= 2:
                cell.add((pp[0].lower().replace("0x", ""),
                          pp[1].lower().replace("0x", "")))

    hs = set(hits)
    print("scanned %d sheets, %d carry a regular tick ladder" % (scanned, len(hs)))
    print("cell-strips.txt entries: %d" % len(cell))
    print("tick sheets ALREADY in cell-strips: %d" % len(hs & cell))
    print("tick sheets NOT in cell-strips  : %d   <- the gap the referee asked about"
          % len(hs - cell))

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Sheets that NEED the even (area-average) reduce at a fractional\n"
                "# factor: a row of >=4 identical-width ink runs, where nearest's\n"
                "# parity would render some ticks 4px and others 5px at f=1.5.\n"
                "# Generated by tools\research\sharp15\make_even_strips.py - do not\n"
                "# hand-edit. Everything NOT in this list takes plain nearest at a\n"
                "# fractional factor and is therefore as crisp as 2x/3x (#200).\n")
        for g, i in sorted(hs | cell):
            f.write("%s %s\n" % (g, i))
    print("wrote %s (%d entries = tick sheets UNION cell-strips)" % (OUT, len(hs | cell)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
