"""gen_codepatches.py - emit C++ site tables from constants.json.

EMITS TEXT ONLY.  It never edits src\\CodePatches.cpp (hard constraint);
paste what you want, after eyes-on, one dialog at a time.

Shapes match the ones CodePatches.cpp already uses:

    struct Imm8Site    { uintptr_t site; uint8_t  stock; };   // 6A ii
    struct Imm32Site   { uintptr_t site; uint32_t stock; };   // 68 ii*4
    struct SubImm8Site { uintptr_t site; uint8_t  stock; };   // 83 /5 ii
    struct RawImm32Site{ uintptr_t site; int immOff; uint8_t op0, op1;
                         uint32_t stock; };                   // lea/add forms

plus one new shape the hand tables never needed:

    struct LeaDisp8Site{ uintptr_t site; int immOff; uint8_t stock; };
                                                              // 8D /r ii

Every entry carries, in its comment: the owning dialog, what the number
positions, the primitive + arg it feeds, its twin sites, the EXPECTED
ORIGINAL BYTES (verify-before-write) and - when round(stock*factor)
exceeds the field - a CLAMP/PIN warning.

Usage:
    python gen_codepatches.py                     # everything, factor 2.0
    python gen_codepatches.py --factor 1.5
    python gen_codepatches.py --only-new          # sites CodePatches lacks
    python gen_codepatches.py --owner 0x78B120    # one builder
    python gen_codepatches.py --out gen.txt
"""
import os
import sys

import common as C

SHAPE = {
    "push_imm8":  ("Imm8Site", "kGenImm8Sites", "{ 0x%06X, 0x%02X }"),
    "push_imm32": ("Imm32Site", "kGenImm32Sites", "{ 0x%06X, 0x%X }"),
    "sub_imm8":   ("SubImm8Site", "kGenSubImm8Sites", "{ 0x%06X, 0x%02X }"),
    "sub_imm32":  ("SubImm32Site", "kGenSubImm32Sites", "{ 0x%06X, 0x%X }"),
    "add_imm8":   ("AddImm8Site", "kGenAddImm8Sites", "{ 0x%06X, 0x%02X }"),
    "lea_disp8":  ("LeaDisp8Site", "kGenLeaDisp8Sites", None),
    "lea_disp32": ("RawImm32Site", "kGenRawImm32Sites", None),
    "add_imm32":  ("RawImm32Site", "kGenRawImm32Sites", None),
    "mov_imm32":  ("RawImm32Site", "kGenRawImm32Sites", None),
    "imul_imm8":  ("ImulImm8Site", "kGenImulImm8Sites", "{ 0x%06X, 0x%02X }"),
}

ROLE_TEXT = {"x": "x", "y": "y", "w": "width", "h": "height",
             "l": "left", "t": "top", "r": "right", "b": "bottom"}


def emit(out, cons, factor, only_new, owner_filter, extras):
    sites = cons["sites"]
    if owner_filter:
        sites = [s for s in sites if int(s["owner"], 16) == owner_filter]
    if only_new:
        sites = [s for s in sites if s["va"] in extras]
    sites = [s for s in sites if s["value"] != 0]

    buckets = {}
    for s in sites:
        sh = SHAPE.get(s["enc"])
        if not sh:
            continue
        buckets.setdefault(sh[1], []).append(s)

    p = out.append
    p("// ==========================================================")
    p("// GENERATED by tools\\uimap\\gen_codepatches.py - DO NOT HAND EDIT.")
    p("//   source : constants.json (census.py -> constants.py)")
    p("//   exe    : SimCity 4.exe 1.1.641.0 Steam, ImageBase 0x400000")
    p("//   factor : %g   (values below are the STOCK numbers; the applier" % factor)
    p("//            writes round(stock * factor), exactly as the existing")
    p("//            CodePatches tables do)")
    p("//   sites  : %d non-zero geometry constants%s" %
      (len(sites), " NOT already in CodePatches.cpp" if only_new else ""))
    p("// Every entry lists its EXPECTED ORIGINAL BYTES: verify before write,")
    p("// mismatch = skip + log, never force.  (METHOD.md 4.5)")
    p("// ==========================================================")
    p("")
    p("struct Imm8Site     { uintptr_t site; uint8_t  stock; };  // 6A ii")
    p("struct Imm32Site    { uintptr_t site; uint32_t stock; };  // 68 ii ii ii ii")
    p("struct SubImm8Site  { uintptr_t site; uint8_t  stock; };  // 83 /5 ii")
    p("struct SubImm32Site { uintptr_t site; uint32_t stock; };  // 81 /5 ii ii ii ii")
    p("struct AddImm8Site  { uintptr_t site; uint8_t  stock; };  // 83 /0 ii")
    p("struct LeaDisp8Site { uintptr_t site; int immOff; uint8_t stock; };  // 8D /r ii")
    p("struct RawImm32Site { uintptr_t site; int immOff; uint8_t op0, op1; uint32_t stock; };")
    p("")

    nclamp = 0
    for tname in sorted(buckets):
        rows = sorted(buckets[tname], key=lambda s: int(s["va"], 16))
        struct = SHAPE[rows[0]["enc"]][0]
        p("const %s %s[] = {" % (struct, tname))
        last_owner = None
        for s in rows:
            va = int(s["va"], 16)
            if s["ownerLabel"] != last_owner:
                p("\t// ---- %s  (builder %s) ----" % (s["ownerLabel"], s["owner"]))
                last_owner = s["ownerLabel"]
            scaled = round(s["value"] * factor)
            warn = ""
            if not s["fits"]:
                nclamp += 1
                warn = ("  !! %d EXCEEDS the %d-byte field (max %d): CLAMP or "
                        "use a runtime pin" % (scaled, s["immSize"], s["ceiling"]))
            enc8 = s["value"] & 0xFF          # two's complement as encoded
            enc32 = s["value"] & 0xFFFFFFFF
            fmt = SHAPE[s["enc"]][2]
            if fmt:
                entry = fmt % (va, enc8 if s["immSize"] == 1 else enc32)
            elif s["enc"] == "lea_disp8":
                entry = "{ 0x%06X, %d, 0x%02X }" % (va, s["immOff"], enc8)
            else:
                b = bytes.fromhex(s["bytes"])
                entry = "{ 0x%06X, %d, 0x%02X, 0x%02X, 0x%X }" % (
                    va, s["immOff"], b[0], b[1] if len(b) > 1 else 0, enc32)
            twins = (" twins " + ",".join(s["twins"])) if s["twins"] else ""
            p("\t%-44s // %s %s via %s; bytes %s -> %d%s%s"
              % (entry + ",", ROLE_TEXT.get(s["role"], s["role"]),
                 "(%d)" % s["value"], s["via"], s["bytes"], scaled, twins, warn))
        p("};")
        p("")

    p("// %d entr%s cannot hold round(stock * %g) in its field - each needs a"
      % (nclamp, "y" if nclamp == 1 else "ies", factor))
    p("// clamp (accepting a tighter-than-ideal value) or a runtime pin.")
    p("")
    p("// --- SHARED FACTORY CONSTANTS (one site, EVERY caller) ---")
    for hc in cons["helperConstants"]:
        p("//   %s = %d at %s (%s, in %s)" %
          (hc["name"], hc["value"], hc["site"], hc["enc"], hc["helper"]))
        for line in hc["note"].split(". "):
            if line.strip():
                p("//       %s" % line.strip())
    return out


def main():
    factor = 2.0
    only_new = "--only-new" in sys.argv
    owner = None
    outpath = None
    for i, a in enumerate(sys.argv):
        if a == "--factor":
            factor = float(sys.argv[i + 1])
        if a == "--owner":
            owner = int(sys.argv[i + 1], 16)
        if a == "--out":
            outpath = sys.argv[i + 1]

    cons = C.jload(os.path.join(C.HERE, "constants.json"))
    if cons is None:
        raise SystemExit("constants.json missing - run constants.py first")
    xc = C.jload(os.path.join(C.WORK, "crosscheck.json"), {"extras": []})
    extras = set(xc.get("extras", []))

    # re-derive the ceiling verdict for the requested factor
    for s in cons["sites"]:
        scaled = round(s["value"] * factor)
        s["fits"] = abs(scaled) <= s["ceiling"]

    lines = emit([], cons, factor, only_new, owner, extras)
    text = "\n".join(lines) + "\n"
    if outpath:
        p = outpath if os.path.isabs(outpath) else os.path.join(C.HERE, outpath)
        with open(p, "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote %s (%d lines)" % (p, len(lines)))
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
